using System.Collections.Generic;
using SabberStoneCore.Model;

namespace SabberStoneCoreAi.Meta
{
	public class DRUIDDecks
	{
		public List<Deck> decks;

		public DRUIDDecks()
		{
			decks = new List<Deck> {
				new Deck(
						"Token_Druid1",
						27000,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Harvest Golem"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("The Forest's Aid"),
						}
						),
				new Deck(
						"Quest_Druid1",
						7600,
						new List<Card>
						{
							Cards.FromName("Crystal Power"),
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Druid of the Scythe"),
							Cards.FromName("Druid of the Scythe"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Tending Tauren"),
						}
						),
				new Deck(
						"Token_Druid2",
						7500,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Harvest Golem"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("Sea Giant"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Quest_Druid2",
						6500,
						new List<Card>
						{
							Cards.FromName("Innervate"),
							Cards.FromName("Innervate"),
							Cards.FromName("Pounce"),
							Cards.FromName("Pounce"),
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Tending Tauren"),
						}
						),
				new Deck(
						"Token_Druid3",
						6300,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Landscaping"),
							Cards.FromName("Landscaping"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("The Forest's Aid"),
						}
						),
				new Deck(
						"Token_Druid4",
						5600,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Crystalsong Portal"),
							Cards.FromName("Crystalsong Portal"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Landscaping"),
							Cards.FromName("Landscaping"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("The Forest's Aid"),
						}
						),
				new Deck(
						"Quest_Druid3",
						3100,
						new List<Card>
						{
							Cards.FromName("Innervate"),
							Cards.FromName("Innervate"),
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Ferocious Howl"),
							Cards.FromName("Ferocious Howl"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Overflow"),
							Cards.FromName("Overflow"),
							Cards.FromName("Cenarius"),
							Cards.FromName("King Phaoris"),
						}
						),
				new Deck(
						"Quest_Druid4",
						2700,
						new List<Card>
						{
							Cards.FromName("Innervate"),
							Cards.FromName("Innervate"),
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Elise the Enlightened"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Ancient of War"),
							Cards.FromName("Ancient of War"),
							Cards.FromName("Cenarius"),
						}
						),
				new Deck(
						"Quest_Druid5",
						2400,
						new List<Card>
						{
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Doomsayer"),
							Cards.FromName("Doomsayer"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Druid of the Scythe"),
							Cards.FromName("Druid of the Scythe"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Cenarius"),
						}
						),
				new Deck(
						"Token_Druid5",
						2100,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("The Forest's Aid"),
						}
						),
				new Deck(
						"Token_Druid6",
						1900,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Acidic Swamp Ooze"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("Sea Giant"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Quest_Druid6",
						1800,
						new List<Card>
						{
							Cards.FromName("Innervate"),
							Cards.FromName("Innervate"),
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Doomsayer"),
							Cards.FromName("Doomsayer"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Elise the Enlightened"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Chef Nomi"),
						}
						),
				new Deck(
						"Token_Druid7",
						1700,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Garden Gnome"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Force of Nature"),
							Cards.FromName("Force of Nature"),
							Cards.FromName("Overflow"),
							Cards.FromName("Overflow"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("The Forest's Aid"),
						}
						),
				new Deck(
						"Highlander_Quest_Druid",
						1600,
						new List<Card>
						{
							Cards.FromName("Crystal Power"),
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Druid of the Scythe"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Swipe"),
							Cards.FromName("Druid of the Claw"),
							Cards.FromName("Elise the Enlightened"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Ancient of War"),
							Cards.FromName("Gloop Sprayer"),
							Cards.FromName("Lucentbark"),
							Cards.FromName("Cenarius"),
						}
						),
				new Deck(
						"Quest_Druid7",
						1500,
						new List<Card>
						{
							Cards.FromName("Innervate"),
							Cards.FromName("Innervate"),
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Swipe"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Elise the Enlightened"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Ancient of War"),
							Cards.FromName("Ancient of War"),
							Cards.FromName("Cenarius"),
						}
						),
				new Deck(
						"Token_Druid8",
						1400,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("The Forest's Aid"),
						}
						),
				new Deck(
						"Quest_Druid8",
						1300,
						new List<Card>
						{
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Garden Gnome"),
							Cards.FromName("Garden Gnome"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Swipe"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Cenarius"),
						}
						),
				new Deck(
						"Quest_Druid9",
						1300,
						new List<Card>
						{
							Cards.FromName("Moonfire"),
							Cards.FromName("Moonfire"),
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Ferocious Howl"),
							Cards.FromName("Ferocious Howl"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Dreampetal Florist"),
							Cards.FromName("Overflow"),
							Cards.FromName("Siamat"),
							Cards.FromName("Malygos"),
						}
						),
				new Deck(
						"Token_Druid9",
						1200,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Harvest Golem"),
							Cards.FromName("Harvest Golem"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("The Forest's Aid"),
						}
						),
				new Deck(
						"Druid1",
						1100,
						new List<Card>
						{
							Cards.FromName("Crystal Power"),
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Druid of the Scythe"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Bone Wraith"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Swipe"),
							Cards.FromName("Druid of the Claw"),
							Cards.FromName("Elise the Enlightened"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Ancient of War"),
							Cards.FromName("Gloop Sprayer"),
							Cards.FromName("Lucentbark"),
							Cards.FromName("Cenarius"),
						}
						),
				new Deck(
						"Token_Druid10",
						1100,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Zilliax"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("Sea Giant"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Quest_Druid10",
						880,
						new List<Card>
						{
							Cards.FromName("Innervate"),
							Cards.FromName("Innervate"),
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Cenarius"),
						}
						),
				new Deck(
						"Token_Druid11",
						880,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Zilliax"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("The Forest's Aid"),
						}
						),
				new Deck(
						"Quest_Druid11",
						860,
						new List<Card>
						{
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Druid of the Scythe"),
							Cards.FromName("Druid of the Scythe"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Cenarius"),
						}
						),
				new Deck(
						"Token_Druid12",
						860,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Landscaping"),
							Cards.FromName("Landscaping"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Eccentric Scribe"),
							Cards.FromName("Eccentric Scribe"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Token_Druid13",
						780,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Zilliax"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("The Forest's Aid"),
						}
						),
				new Deck(
						"Quest_Druid12",
						750,
						new List<Card>
						{
							Cards.FromName("Innervate"),
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Cenarius"),
						}
						),
				new Deck(
						"Quest_Druid13",
						670,
						new List<Card>
						{
							Cards.FromName("Crystal Power"),
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Wrath"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Druid of the Scythe"),
							Cards.FromName("Mischief Maker"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Cult Master"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Swipe"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Druid of the Claw"),
							Cards.FromName("Elise the Enlightened"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Ancient of War"),
							Cards.FromName("Overflow"),
							Cards.FromName("Cenarius"),
						}
						),
				new Deck(
						"Quest_Druid14",
						660,
						new List<Card>
						{
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Swipe"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Overflow"),
							Cards.FromName("Cenarius"),
						}
						),
				new Deck(
						"Heal_Druid1",
						660,
						new List<Card>
						{
							Cards.FromName("Crystal Power"),
							Cards.FromName("Crystal Power"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Ferocious Howl"),
							Cards.FromName("Ferocious Howl"),
							Cards.FromName("Healing Touch"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Witching Hour"),
							Cards.FromName("Witching Hour"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Juicy Psychmelon"),
							Cards.FromName("Predatory Instincts"),
							Cards.FromName("Predatory Instincts"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Ancient of Lore"),
							Cards.FromName("Ancient of Lore"),
							Cards.FromName("Gloop Sprayer"),
							Cards.FromName("Lucentbark"),
						}
						),
				new Deck(
						"Quest_Druid15",
						650,
						new List<Card>
						{
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Druid of the Scythe"),
							Cards.FromName("Druid of the Scythe"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Druid of the Claw"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Cenarius"),
						}
						),
				new Deck(
						"Token_Druid14",
						620,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Harvest Golem"),
							Cards.FromName("Harvest Golem"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("The Forest's Aid"),
						}
						),
				new Deck(
						"Druid2",
						600,
						new List<Card>
						{
							Cards.FromName("Innervate"),
							Cards.FromName("Moonfire"),
							Cards.FromName("Moonfire"),
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Ferocious Howl"),
							Cards.FromName("Ferocious Howl"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Elise the Enlightened"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Dreampetal Florist"),
							Cards.FromName("Malygos"),
						}
						),
				new Deck(
						"Druid3",
						590,
						new List<Card>
						{
							Cards.FromName("Innervate"),
							Cards.FromName("Innervate"),
							Cards.FromName("Moonfire"),
							Cards.FromName("Moonfire"),
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Ferocious Howl"),
							Cards.FromName("Ferocious Howl"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Elise the Enlightened"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Dreampetal Florist"),
							Cards.FromName("Malygos"),
						}
						),
				new Deck(
						"Quest_Druid16",
						590,
						new List<Card>
						{
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Druid of the Scythe"),
							Cards.FromName("Druid of the Scythe"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Druid of the Claw"),
							Cards.FromName("Druid of the Claw"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Ancient of War"),
							Cards.FromName("Ancient of War"),
							Cards.FromName("Cenarius"),
						}
						),
				new Deck(
						"Druid4",
						570,
						new List<Card>
						{
							Cards.FromName("Innervate"),
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Doomsayer"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Elise the Enlightened"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Cenarius"),
						}
						),
				new Deck(
						"Token_Druid15",
						530,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("The Forest's Aid"),
						}
						),
				new Deck(
						"Token_Druid16",
						520,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("Sea Giant"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Heal_Druid2",
						520,
						new List<Card>
						{
							Cards.FromName("Crystal Power"),
							Cards.FromName("Crystal Power"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Earthen Ring Farseer"),
							Cards.FromName("Earthen Ring Farseer"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Lifeweaver"),
							Cards.FromName("Lifeweaver"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Crystal Stag"),
							Cards.FromName("Crystal Stag"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Ancient of Lore"),
							Cards.FromName("Ancient of Lore"),
							Cards.FromName("Countess Ashmore"),
							Cards.FromName("Lucentbark"),
						}
						),
				new Deck(
						"Token_Druid17",
						520,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Floop's Glorious Gloop"),
							Cards.FromName("Dendrologist"),
							Cards.FromName("Dendrologist"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Landscaping"),
							Cards.FromName("Landscaping"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Force of Nature"),
							Cards.FromName("Force of Nature"),
							Cards.FromName("Treespeaker"),
							Cards.FromName("Treespeaker"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("Cenarius"),
							Cards.FromName("Mulchmuncher"),
							Cards.FromName("Mulchmuncher"),
						}
						),
				new Deck(
						"Druid5",
						490,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Landscaping"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Garden Gnome"),
							Cards.FromName("Garden Gnome"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Swipe"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Force of Nature"),
							Cards.FromName("Force of Nature"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("Mulchmuncher"),
							Cards.FromName("Mulchmuncher"),
						}
						),
				new Deck(
						"Quest_Druid17",
						450,
						new List<Card>
						{
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Druid of the Scythe"),
							Cards.FromName("Druid of the Scythe"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Elise the Enlightened"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Overflow"),
							Cards.FromName("Cenarius"),
						}
						),
				new Deck(
						"Token_Druid18",
						450,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Dendrologist"),
							Cards.FromName("Dendrologist"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Landscaping"),
							Cards.FromName("Landscaping"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Force of Nature"),
							Cards.FromName("Force of Nature"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Token_Druid19",
						440,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Acidic Swamp Ooze"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Landscaping"),
							Cards.FromName("Landscaping"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Soul of the Forest"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Wispering Woods"),
							Cards.FromName("Eccentric Scribe"),
							Cards.FromName("The Forest's Aid"),
							Cards.FromName("The Forest's Aid"),
						}
						),
				new Deck(
						"Quest_Druid18",
						410,
						new List<Card>
						{
							Cards.FromName("Innervate"),
							Cards.FromName("Untapped Potential"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Worthy Expedition"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Crystal Merchant"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("BEEEES!!!"),
							Cards.FromName("Wardruid Loti"),
							Cards.FromName("Flobbidinous Floop"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Anubisath Defender"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Oasis Surger"),
							Cards.FromName("Starfall"),
							Cards.FromName("Starfall"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Hidden Oasis"),
							Cards.FromName("Nourish"),
							Cards.FromName("Nourish"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Tending Tauren"),
							Cards.FromName("Cenarius"),
							Cards.FromName("King Phaoris"),
						}
						),
				new Deck(
						"Token_Druid20",
						410,
						new List<Card>
						{
							Cards.FromName("Acornbearer"),
							Cards.FromName("Acornbearer"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Dreamway Guardians"),
							Cards.FromName("Keeper Stalladris"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Power of the Wild"),
							Cards.FromName("Wrath"),
							Cards.FromName("Wrath"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Blessing of the Ancients"),
							Cards.FromName("Landscaping"),
							Cards.FromName("Landscaping"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("Savage Roar"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Mark of the Loa"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Swipe"),
							Cards.FromName("Swipe"),
							Cards.FromName("The Forest's Aid"),
						}
						)
				};
		}
	}
}