using System.Collections.Generic;
using SabberStoneCore.Model;
using SabberStoneCore.Enums;

namespace SabberStoneCoreAi.Meta
{
	public class PALADINDecks
	{
		public List<Deck> decks;

		public PALADINDecks()
		{
			decks = new List<Deck> {
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin1",
						26000,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin2",
						10000,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Salhet's Pride"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Quest_Paladin1",
						8100,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Making Mummies"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Micro Mummy"),
							Cards.FromName("Micro Mummy"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Temple Berserker"),
							Cards.FromName("Temple Berserker"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Candletaker"),
							Cards.FromName("Candletaker"),
							Cards.FromName("Ancestral Guardian"),
							Cards.FromName("Ancestral Guardian"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Bone Wraith"),
							Cards.FromName("Bone Wraith"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Kangor's Endless Army"),
							Cards.FromName("Da Undatakah"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin3",
						6700,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Mech_Paladin1",
						6000,
						new List<Card>
						{
							Cards.FromName("Blessing of Wisdom"),
							Cards.FromName("Blessing of Wisdom"),
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("High Priest Thekal"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Rusty Recycler"),
							Cards.FromName("Rusty Recycler"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Kangor's Endless Army"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Quest_Paladin2",
						5900,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Making Mummies"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Micro Mummy"),
							Cards.FromName("Micro Mummy"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Temple Berserker"),
							Cards.FromName("Temple Berserker"),
							Cards.FromName("Candletaker"),
							Cards.FromName("Candletaker"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Ancestral Guardian"),
							Cards.FromName("Ancestral Guardian"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Bone Wraith"),
							Cards.FromName("Bone Wraith"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Kangor's Endless Army"),
							Cards.FromName("Da Undatakah"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin4",
						5900,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Mech_Paladin2",
						4400,
						new List<Card>
						{
							Cards.FromName("Blessing of Wisdom"),
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Lightforged Blessing"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Consecration"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Kangor's Endless Army"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin5",
						3900,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Raider"),
							Cards.FromName("Murloc Raider"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Paladin1",
						2900,
						new List<Card>
						{
							Cards.FromName("Blessing of Wisdom"),
							Cards.FromName("Blessing of Wisdom"),
							Cards.FromName("Desperate Measures"),
							Cards.FromName("Never Surrender!"),
							Cards.FromName("Never Surrender!"),
							Cards.FromName("Noble Sacrifice"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Rebuke"),
							Cards.FromName("Rebuke"),
							Cards.FromName("Subdue"),
							Cards.FromName("Subdue"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Avenging Wrath"),
							Cards.FromName("Avenging Wrath"),
							Cards.FromName("A New Challenger..."),
							Cards.FromName("A New Challenger..."),
							Cards.FromName("Lay on Hands"),
							Cards.FromName("Lay on Hands"),
							Cards.FromName("King Phaoris"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Holy_Wrath_Paladin1",
						2900,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Elven Archer"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("Crystalsmith Kangor"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Mech_Paladin3",
						2700,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Lightforged Blessing"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Kangor's Endless Army"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Quest_Paladin3",
						2400,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Making Mummies"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Micro Mummy"),
							Cards.FromName("Micro Mummy"),
							Cards.FromName("Subdue"),
							Cards.FromName("Subdue"),
							Cards.FromName("Temple Berserker"),
							Cards.FromName("Temple Berserker"),
							Cards.FromName("Candletaker"),
							Cards.FromName("Candletaker"),
							Cards.FromName("Ancestral Guardian"),
							Cards.FromName("Ancestral Guardian"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Bone Wraith"),
							Cards.FromName("Bone Wraith"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Kangor's Endless Army"),
							Cards.FromName("Siamat"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Mech_Paladin4",
						2200,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Coppertail Imposter"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Countess Ashmore"),
							Cards.FromName("Kangor's Endless Army"),
							Cards.FromName("Tirion Fordring"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin6",
						2200,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Holy_Wrath_Paladin2",
						2100,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Elven Archer"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("Crystalsmith Kangor"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Equality"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Mech_Paladin5",
						1900,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Lightforged Blessing"),
							Cards.FromName("Aldor Peacekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Coppertail Imposter"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Kangor's Endless Army"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Big_Paladin1",
						1800,
						new List<Card>
						{
							Cards.FromName("Desperate Measures"),
							Cards.FromName("Desperate Measures"),
							Cards.FromName("Redemption"),
							Cards.FromName("Lightforged Blessing"),
							Cards.FromName("Mysterious Blade"),
							Cards.FromName("Mysterious Blade"),
							Cards.FromName("Subdue"),
							Cards.FromName("Subdue"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Duel!"),
							Cards.FromName("Duel!"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blatant Decoy"),
							Cards.FromName("Blatant Decoy"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Kangor's Endless Army"),
							Cards.FromName("Tirion Fordring"),
							Cards.FromName("Bull Dozer"),
							Cards.FromName("Bull Dozer"),
							Cards.FromName("Colossus of the Moon"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Mech_Paladin6",
						1700,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Lightforged Blessing"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Countess Ashmore"),
							Cards.FromName("Kangor's Endless Army"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin7",
						1600,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Raider"),
							Cards.FromName("Murloc Raider"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin8",
						1400,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Loot Hoarder"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Paladin2",
						1300,
						new List<Card>
						{
							Cards.FromName("Beaming Sidekick"),
							Cards.FromName("Beaming Sidekick"),
							Cards.FromName("Brazen Zealot"),
							Cards.FromName("Brazen Zealot"),
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Jar Dealer"),
							Cards.FromName("Jar Dealer"),
							Cards.FromName("Argent Protector"),
							Cards.FromName("Argent Protector"),
							Cards.FromName("Sandwasp Queen"),
							Cards.FromName("Sandwasp Queen"),
							Cards.FromName("Faceless Rager"),
							Cards.FromName("Faceless Rager"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Salhet's Pride"),
							Cards.FromName("Salhet's Pride"),
							Cards.FromName("Blessing of Kings"),
							Cards.FromName("Blessing of Kings"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Pharaoh's Blessing"),
							Cards.FromName("Pharaoh's Blessing"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin9",
						1300,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin10",
						1200,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Salhet's Pride"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Holy_Wrath_Paladin3",
						1200,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Elven Archer"),
							Cards.FromName("Elven Archer"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Crystalsmith Kangor"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Equality"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Paladin3",
						1200,
						new List<Card>
						{
							Cards.FromName("Blessing of Wisdom"),
							Cards.FromName("Desperate Measures"),
							Cards.FromName("Desperate Measures"),
							Cards.FromName("Redemption"),
							Cards.FromName("Redemption"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Mysterious Blade"),
							Cards.FromName("Mysterious Blade"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Duel!"),
							Cards.FromName("Duel!"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blatant Decoy"),
							Cards.FromName("Blatant Decoy"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Kangor's Endless Army"),
							Cards.FromName("Tirion Fordring"),
							Cards.FromName("Bull Dozer"),
							Cards.FromName("Bull Dozer"),
							Cards.FromName("Colossus of the Moon"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Paladin4",
						1100,
						new List<Card>
						{
							Cards.FromName("Blessing of Wisdom"),
							Cards.FromName("Crystology"),
							Cards.FromName("Elven Archer"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Crystalsmith Kangor"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Immortal Prelate"),
							Cards.FromName("Lightforged Blessing"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Subdue"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Blessing of Kings"),
							Cards.FromName("Consecration"),
							Cards.FromName("Equality"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Da Undatakah"),
							Cards.FromName("Lay on Hands"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Quest_Paladin4",
						1100,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Making Mummies"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Micro Mummy"),
							Cards.FromName("Micro Mummy"),
							Cards.FromName("Temple Berserker"),
							Cards.FromName("Temple Berserker"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Candletaker"),
							Cards.FromName("Candletaker"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Bone Wraith"),
							Cards.FromName("Bone Wraith"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Countess Ashmore"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Holy_Wrath_Paladin4",
						1100,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Elven Archer"),
							Cards.FromName("Elven Archer"),
							Cards.FromName("Stonetusk Boar"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("Crystalsmith Kangor"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Loot Hoarder"),
							Cards.FromName("Loot Hoarder"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Subdue"),
							Cards.FromName("Subdue"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Salhet's Pride"),
							Cards.FromName("Salhet's Pride"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Consecration"),
							Cards.FromName("Equality"),
							Cards.FromName("Equality"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin11",
						1100,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Raider"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin12",
						1000,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin13",
						1000,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Holy_Wrath_Paladin5",
						1000,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Elven Archer"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("Crystalsmith Kangor"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Loot Hoarder"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Subdue"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Youthful Brewmaster"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Golden Scarab"),
							Cards.FromName("Salhet's Pride"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Consecration"),
							Cards.FromName("Equality"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Sandbinder"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Siamat"),
							Cards.FromName("Tirion Fordring"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin14",
						1000,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Paladin5",
						1000,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin15",
						980,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Micro Mummy"),
							Cards.FromName("Micro Mummy"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin16",
						960,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Witch's Cauldron"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin17",
						950,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin18",
						920,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Mech_Paladin7",
						920,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Lightforged Blessing"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Coppertail Imposter"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Kangor's Endless Army"),
							Cards.FromName("Tirion Fordring"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Mech_Paladin8",
						920,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Lightforged Blessing"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Kangor's Endless Army"),
							Cards.FromName("Tirion Fordring"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin19",
						910,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Holy_Wrath_Paladin6",
						900,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Elven Archer"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("Crystalsmith Kangor"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Equality"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Holy_Wrath_Paladin7",
						890,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Hungry Crab"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("Crystalsmith Kangor"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Equality"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Tirion Fordring"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Holy_Wrath_Paladin8",
						860,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Elven Archer"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("Crystalsmith Kangor"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Equality"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Alexstrasza"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin20",
						810,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Mech_Paladin9",
						800,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Lightforged Blessing"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Arcane Dynamo"),
							Cards.FromName("Kangor's Endless Army"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin21",
						780,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Cult Master"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Big_Paladin2",
						780,
						new List<Card>
						{
							Cards.FromName("Desperate Measures"),
							Cards.FromName("Desperate Measures"),
							Cards.FromName("Mysterious Blade"),
							Cards.FromName("Mysterious Blade"),
							Cards.FromName("Subdue"),
							Cards.FromName("Subdue"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Duel!"),
							Cards.FromName("Duel!"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blatant Decoy"),
							Cards.FromName("Blatant Decoy"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Kangor's Endless Army"),
							Cards.FromName("Tirion Fordring"),
							Cards.FromName("Bull Dozer"),
							Cards.FromName("Bull Dozer"),
							Cards.FromName("Colossus of the Moon"),
							Cards.FromName("Mountain Giant"),
							Cards.FromName("Mountain Giant"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin22",
						750,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Salhet's Pride"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin23",
						690,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Secret_Paladin",
						660,
						new List<Card>
						{
							Cards.FromName("Autodefense Matrix"),
							Cards.FromName("Autodefense Matrix"),
							Cards.FromName("Desperate Measures"),
							Cards.FromName("Desperate Measures"),
							Cards.FromName("Hidden Wisdom"),
							Cards.FromName("Never Surrender!"),
							Cards.FromName("Never Surrender!"),
							Cards.FromName("Noble Sacrifice"),
							Cards.FromName("Redemption"),
							Cards.FromName("Secretkeeper"),
							Cards.FromName("Secretkeeper"),
							Cards.FromName("Mysterious Blade"),
							Cards.FromName("Mysterious Blade"),
							Cards.FromName("Sunreaver Spy"),
							Cards.FromName("Sunreaver Spy"),
							Cards.FromName("Commander Rhyssa"),
							Cards.FromName("Masked Contender"),
							Cards.FromName("Masked Contender"),
							Cards.FromName("Bellringer Sentry"),
							Cards.FromName("Bellringer Sentry"),
							Cards.FromName("Blessing of Kings"),
							Cards.FromName("Blessing of Kings"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Subject 9"),
							Cards.FromName("Pharaoh's Blessing"),
							Cards.FromName("Pharaoh's Blessing"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Mech_Paladin10",
						630,
						new List<Card>
						{
							Cards.FromName("Blessing of Wisdom"),
							Cards.FromName("Blessing of Wisdom"),
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Consecration"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Rusty Recycler"),
							Cards.FromName("Rusty Recycler"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Kangor's Endless Army"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Big_Paladin3",
						630,
						new List<Card>
						{
							Cards.FromName("Desperate Measures"),
							Cards.FromName("Redemption"),
							Cards.FromName("Redemption"),
							Cards.FromName("Lightforged Blessing"),
							Cards.FromName("Mysterious Blade"),
							Cards.FromName("Mysterious Blade"),
							Cards.FromName("Subdue"),
							Cards.FromName("Subdue"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Duel!"),
							Cards.FromName("Duel!"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blatant Decoy"),
							Cards.FromName("Blatant Decoy"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Kangor's Endless Army"),
							Cards.FromName("Tirion Fordring"),
							Cards.FromName("Bull Dozer"),
							Cards.FromName("Bull Dozer"),
							Cards.FromName("Colossus of the Moon"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Big_Paladin4",
						630,
						new List<Card>
						{
							Cards.FromName("Desperate Measures"),
							Cards.FromName("Desperate Measures"),
							Cards.FromName("Redemption"),
							Cards.FromName("Redemption"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Mysterious Blade"),
							Cards.FromName("Mysterious Blade"),
							Cards.FromName("Subdue"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Duel!"),
							Cards.FromName("Duel!"),
							Cards.FromName("Blatant Decoy"),
							Cards.FromName("Blatant Decoy"),
							Cards.FromName("Batterhead"),
							Cards.FromName("Batterhead"),
							Cards.FromName("Tirion Fordring"),
							Cards.FromName("Ysera"),
							Cards.FromName("Colossus of the Moon"),
							Cards.FromName("Living Monument"),
							Cards.FromName("Living Monument"),
							Cards.FromName("Mountain Giant"),
							Cards.FromName("Mountain Giant"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin24",
						620,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Salhet's Pride"),
							Cards.FromName("Salhet's Pride"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin25",
						610,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("History Buff"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Big_Paladin5",
						600,
						new List<Card>
						{
							Cards.FromName("Desperate Measures"),
							Cards.FromName("Desperate Measures"),
							Cards.FromName("Redemption"),
							Cards.FromName("Redemption"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Lightforged Blessing"),
							Cards.FromName("Mysterious Blade"),
							Cards.FromName("Mysterious Blade"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Duel!"),
							Cards.FromName("Duel!"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Kangor's Endless Army"),
							Cards.FromName("Batterhead"),
							Cards.FromName("Batterhead"),
							Cards.FromName("Tirion Fordring"),
							Cards.FromName("Alexstrasza"),
							Cards.FromName("Bull Dozer"),
							Cards.FromName("Bull Dozer"),
							Cards.FromName("Ysera"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin26",
						560,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Big_Paladin6",
						550,
						new List<Card>
						{
							Cards.FromName("Desperate Measures"),
							Cards.FromName("Desperate Measures"),
							Cards.FromName("Redemption"),
							Cards.FromName("Redemption"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Lightforged Blessing"),
							Cards.FromName("Mysterious Blade"),
							Cards.FromName("Mysterious Blade"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Duel!"),
							Cards.FromName("Duel!"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Kangor's Endless Army"),
							Cards.FromName("Tirion Fordring"),
							Cards.FromName("Alexstrasza"),
							Cards.FromName("Bull Dozer"),
							Cards.FromName("Bull Dozer"),
							Cards.FromName("Ysera"),
							Cards.FromName("Mountain Giant"),
							Cards.FromName("Mountain Giant"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Paladin6",
						540,
						new List<Card>
						{
							Cards.FromName("Crystalsmith Kangor"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Immortal Prelate"),
							Cards.FromName("Immortal Prelate"),
							Cards.FromName("Lightforged Blessing"),
							Cards.FromName("Lightforged Blessing"),
							Cards.FromName("Sound the Bells!"),
							Cards.FromName("Sound the Bells!"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("High Priest Thekal"),
							Cards.FromName("Blessing of Kings"),
							Cards.FromName("Blessing of Kings"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Equality"),
							Cards.FromName("Equality"),
							Cards.FromName("Spirit of the Tiger"),
							Cards.FromName("Spirit of the Tiger"),
							Cards.FromName("Farraki Battleaxe"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Zilliax"),
							Cards.FromName("A New Challenger..."),
							Cards.FromName("Countess Ashmore"),
							Cards.FromName("Lay on Hands"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Holy_Wrath_Paladin9",
						520,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Elven Archer"),
							Cards.FromName("Elven Archer"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("Crystalsmith Kangor"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Equality"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Mech_Paladin11",
						510,
						new List<Card>
						{
							Cards.FromName("Blessing of Wisdom"),
							Cards.FromName("Blessing of Wisdom"),
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Rusty Recycler"),
							Cards.FromName("Rusty Recycler"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Kangor's Endless Army"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Mech_Paladin12",
						510,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Wargear"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Kangor's Endless Army"),
							Cards.FromName("Lay on Hands"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin27",
						510,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Paladin7",
						510,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Holy_Wrath_Paladin10",
						460,
						new List<Card>
						{
							Cards.FromName("Bloodsail Corsair"),
							Cards.FromName("Bloodsail Corsair"),
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("Crystalsmith Kangor"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Alexstrasza"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Mech_Paladin13",
						440,
						new List<Card>
						{
							Cards.FromName("Blessing of Wisdom"),
							Cards.FromName("Blessing of Wisdom"),
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Glow-Tron"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Skaterbot"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("Call to Adventure"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Annoy-o-Module"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Glowstone Technician"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Mechano-Egg"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Missile Launcher"),
							Cards.FromName("Kangor's Endless Army"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Murloc_Paladin28",
						410,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Hungry Crab"),
							Cards.FromName("Hungry Crab"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Sir Finley of the Sands"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Tip the Scales"),
							Cards.FromName("Tip the Scales"),
						}
						),
				new Deck(CardClass.PALADIN,
						"Holy_Wrath_Paladin11",
						410,
						new List<Card>
						{
							Cards.FromName("Crystology"),
							Cards.FromName("Crystology"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("Crystalsmith Kangor"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Flash of Light"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Time Out!"),
							Cards.FromName("Consecration"),
							Cards.FromName("Consecration"),
							Cards.FromName("Equality"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Hammer of Wrath"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Prismatic Lens"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Truesilver Champion"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Holy Wrath"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Shrink Ray"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Shirvallah, the Tiger"),
						}
						)
				};
		}
	}
}
