using System.Collections.Generic;
using SabberStoneCore.Model;

namespace SabberStoneCoreAi.Meta
{
	public class PRIESTDecks
	{
		public List<Deck> decks;

		public PRIESTDecks()
		{
			decks = new List<Deck> {
				new Deck(
						"Quest_Priest1",
						8700,
						new List<Card>
						{
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Activate the Obelisk"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Penance"),
							Cards.FromName("Penance"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Catrina Muerte"),
							Cards.FromName("Mosh'Ogg Enforcer"),
							Cards.FromName("Mosh'Ogg Enforcer"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Plague of Death"),
							Cards.FromName("Plague of Death"),
							Cards.FromName("King Phaoris"),
						}
						),
				new Deck(
						"Quest_Priest2",
						5600,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Activate the Obelisk"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Vivid Nightmare"),
							Cards.FromName("High Priest Amet"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Zilliax"),
						}
						),
				new Deck(
						"Priest1",
						3600,
						new List<Card>
						{
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Activate the Obelisk"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Penance"),
							Cards.FromName("Penance"),
							Cards.FromName("Seance"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Bone Wraith"),
							Cards.FromName("Bone Wraith"),
							Cards.FromName("High Priest Amet"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Khartut Defender"),
							Cards.FromName("Khartut Defender"),
							Cards.FromName("Catrina Muerte"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Plague of Death"),
							Cards.FromName("Plague of Death"),
						}
						),
				new Deck(
						"Quest_Priest3",
						3200,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Activate the Obelisk"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Holy Ripple"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Neferset Ritualist"),
							Cards.FromName("Neferset Ritualist"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Hench-Clan Shadequill"),
							Cards.FromName("High Priest Amet"),
							Cards.FromName("Zilliax"),
						}
						),
				new Deck(
						"Quest_Priest4",
						3100,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Activate the Obelisk"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Ornery Tortoise"),
							Cards.FromName("Ornery Tortoise"),
							Cards.FromName("High Priest Amet"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Zilliax"),
						}
						),
				new Deck(
						"Priest2",
						2900,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Lightwarden"),
							Cards.FromName("Lightwarden"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Holy Ripple"),
							Cards.FromName("Holy Ripple"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Neferset Ritualist"),
							Cards.FromName("Neferset Ritualist"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("High Priest Amet"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Psychopomp"),
						}
						),
				new Deck(
						"Mech_Priest1",
						2500,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Silence"),
							Cards.FromName("Silence"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Upgradeable Framebot"),
							Cards.FromName("Upgradeable Framebot"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Coppertail Imposter"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Unpowered Steambot"),
							Cards.FromName("Unpowered Steambot"),
							Cards.FromName("Zilliax"),
						}
						),
				new Deck(
						"Silence_Priest1",
						2500,
						new List<Card>
						{
							Cards.FromName("Silence"),
							Cards.FromName("Silence"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Ancient Watcher"),
							Cards.FromName("Ancient Watcher"),
							Cards.FromName("Dalaran Librarian"),
							Cards.FromName("Dalaran Librarian"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Arcane Watcher"),
							Cards.FromName("Arcane Watcher"),
							Cards.FromName("Faceless Rager"),
							Cards.FromName("Faceless Rager"),
							Cards.FromName("Hench-Clan Shadequill"),
							Cards.FromName("Hench-Clan Shadequill"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Unsleeping Soul"),
							Cards.FromName("Unsleeping Soul"),
							Cards.FromName("Holy Nova"),
							Cards.FromName("Holy Nova"),
							Cards.FromName("Quartz Elemental"),
							Cards.FromName("Quartz Elemental"),
						}
						),
				new Deck(
						"Combo_Priest1",
						2500,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Activate the Obelisk"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("High Priest Amet"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Sandhoof Waterbearer"),
						}
						),
				new Deck(
						"Silence_Priest2",
						2200,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Silence"),
							Cards.FromName("Silence"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Ancient Watcher"),
							Cards.FromName("Ancient Watcher"),
							Cards.FromName("Dalaran Librarian"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Sunfury Protector"),
							Cards.FromName("Upgradeable Framebot"),
							Cards.FromName("Upgradeable Framebot"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Arcane Watcher"),
							Cards.FromName("Arcane Watcher"),
							Cards.FromName("Faceless Rager"),
							Cards.FromName("Faceless Rager"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Hench-Clan Shadequill"),
							Cards.FromName("Unsleeping Soul"),
						}
						),
				new Deck(
						"Resurrect_Priest1",
						2200,
						new List<Card>
						{
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Seance"),
							Cards.FromName("Seance"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Holy Nova"),
							Cards.FromName("Holy Nova"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Catrina Muerte"),
							Cards.FromName("Mosh'Ogg Enforcer"),
							Cards.FromName("Mosh'Ogg Enforcer"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Mass Resurrection"),
						}
						),
				new Deck(
						"Quest_Priest5",
						2000,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Activate the Obelisk"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Spirit of the Dead"),
							Cards.FromName("Dead Ringer"),
							Cards.FromName("Dead Ringer"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Hench-Clan Shadequill"),
							Cards.FromName("Hench-Clan Shadequill"),
							Cards.FromName("High Priest Amet"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Octosari"),
						}
						),
				new Deck(
						"Combo_Priest2",
						1500,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Silence"),
							Cards.FromName("Silence"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Sand Drudge"),
							Cards.FromName("High Priest Amet"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Stormwind Knight"),
						}
						),
				new Deck(
						"Combo_Priest3",
						1400,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Silence"),
							Cards.FromName("Silence"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Banana Buffoon"),
							Cards.FromName("Banana Buffoon"),
							Cards.FromName("Half-Time Scavenger"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Grave Horror"),
							Cards.FromName("Grave Horror"),
							Cards.FromName("Mountain Giant"),
							Cards.FromName("Mountain Giant"),
						}
						),
				new Deck(
						"Resurrect_Priest2",
						1100,
						new List<Card>
						{
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Shadow Word: Pain"),
							Cards.FromName("Omega Medic"),
							Cards.FromName("Omega Medic"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Proud Defender"),
							Cards.FromName("Proud Defender"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Holy Nova"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Catrina Muerte"),
							Cards.FromName("Mosh'Ogg Enforcer"),
							Cards.FromName("Mosh'Ogg Enforcer"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Mass Resurrection"),
						}
						),
				new Deck(
						"Combo_Priest4",
						1000,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Silence"),
							Cards.FromName("Silence"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Penance"),
							Cards.FromName("Penance"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("High Priest Amet"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Psychopomp"),
						}
						),
				new Deck(
						"Combo_Priest5",
						970,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Silence"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Spirit of the Dead"),
							Cards.FromName("Spirit of the Dead"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Banana Buffoon"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Bwonsamdi, the Dead"),
							Cards.FromName("Grave Horror"),
							Cards.FromName("Grave Horror"),
							Cards.FromName("Mountain Giant"),
							Cards.FromName("Mountain Giant"),
						}
						),
				new Deck(
						"Resurrect_Priest3",
						870,
						new List<Card>
						{
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Seance"),
							Cards.FromName("Seance"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Holy Nova"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Catrina Muerte"),
							Cards.FromName("Mosh'Ogg Enforcer"),
							Cards.FromName("Mosh'Ogg Enforcer"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Mass Resurrection"),
						}
						),
				new Deck(
						"Resurrect_Priest4",
						810,
						new List<Card>
						{
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Shadow Word: Pain"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Hench-Clan Shadequill"),
							Cards.FromName("Shadow Madness"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Catrina Muerte"),
							Cards.FromName("Mosh'Ogg Enforcer"),
							Cards.FromName("Mosh'Ogg Enforcer"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Mass Resurrection"),
						}
						),
				new Deck(
						"Mech_Priest2",
						810,
						new List<Card>
						{
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Dead Ringer"),
							Cards.FromName("Dead Ringer"),
							Cards.FromName("EVIL Conscripter"),
							Cards.FromName("EVIL Conscripter"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Grandmummy"),
							Cards.FromName("Grandmummy"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Wretched Reclaimer"),
							Cards.FromName("Wretched Reclaimer"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
							Cards.FromName("Zilliax"),
						}
						),
				new Deck(
						"Nomi_Priest1",
						810,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Lazul's Scheme"),
							Cards.FromName("Lazul's Scheme"),
							Cards.FromName("Regenerate"),
							Cards.FromName("Regenerate"),
							Cards.FromName("Silence"),
							Cards.FromName("Silence"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Holy Smite"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Seance"),
							Cards.FromName("Seance"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Gadgetzan Auctioneer"),
							Cards.FromName("Gadgetzan Auctioneer"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Grave Horror"),
							Cards.FromName("Grave Horror"),
						}
						),
				new Deck(
						"Quest_Priest6",
						780,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Activate the Obelisk"),
							Cards.FromName("Lightwarden"),
							Cards.FromName("Lightwarden"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Holy Ripple"),
							Cards.FromName("Holy Ripple"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Recurring Villain"),
							Cards.FromName("Recurring Villain"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Zilliax"),
						}
						),
				new Deck(
						"Resurrect_Priest5",
						760,
						new List<Card>
						{
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Seance"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Proud Defender"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Holy Nova"),
							Cards.FromName("Holy Nova"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Tunnel Blaster"),
							Cards.FromName("Catrina Muerte"),
							Cards.FromName("Mosh'Ogg Enforcer"),
							Cards.FromName("Mosh'Ogg Enforcer"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Mass Resurrection"),
						}
						),
				new Deck(
						"Priest3",
						720,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Activate the Obelisk"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Spirit of the Dead"),
							Cards.FromName("Spirit of the Dead"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Holy Ripple"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Seance"),
							Cards.FromName("Seance"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("High Priest Amet"),
							Cards.FromName("Bwonsamdi, the Dead"),
							Cards.FromName("Grave Horror"),
							Cards.FromName("Grave Horror"),
						}
						),
				new Deck(
						"Combo_Priest6",
						720,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Silence"),
							Cards.FromName("Silence"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Banana Buffoon"),
							Cards.FromName("Banana Buffoon"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Recurring Villain"),
							Cards.FromName("Grave Horror"),
							Cards.FromName("Grave Horror"),
							Cards.FromName("Mountain Giant"),
							Cards.FromName("Mountain Giant"),
						}
						),
				new Deck(
						"Combo_Priest7",
						690,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Wretched Reclaimer"),
							Cards.FromName("Wretched Reclaimer"),
							Cards.FromName("High Priest Amet"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Zilliax"),
						}
						),
				new Deck(
						"Resurrect_Priest6",
						690,
						new List<Card>
						{
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Shadow Word: Pain"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Mosh'Ogg Announcer"),
							Cards.FromName("Mosh'Ogg Announcer"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Batterhead"),
							Cards.FromName("Catrina Muerte"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Plague of Death"),
						}
						),
				new Deck(
						"Nomi_Priest2",
						690,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Lazul's Scheme"),
							Cards.FromName("Lazul's Scheme"),
							Cards.FromName("Regenerate"),
							Cards.FromName("Regenerate"),
							Cards.FromName("Silence"),
							Cards.FromName("Silence"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Seance"),
							Cards.FromName("Seance"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Gadgetzan Auctioneer"),
							Cards.FromName("Gadgetzan Auctioneer"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Grave Horror"),
							Cards.FromName("Grave Horror"),
						}
						),
				new Deck(
						"Mech_Priest3",
						680,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Silence"),
							Cards.FromName("Silence"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Upgradeable Framebot"),
							Cards.FromName("Upgradeable Framebot"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Coppertail Imposter"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Unpowered Steambot"),
							Cards.FromName("Unpowered Steambot"),
							Cards.FromName("Witchwood Piper"),
							Cards.FromName("Witchwood Piper"),
							Cards.FromName("Zilliax"),
						}
						),
				new Deck(
						"Mech_Priest4",
						650,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Silence"),
							Cards.FromName("Silence"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Upgradeable Framebot"),
							Cards.FromName("Upgradeable Framebot"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Stormwind Knight"),
							Cards.FromName("Unpowered Steambot"),
							Cards.FromName("Unpowered Steambot"),
							Cards.FromName("Witchwood Piper"),
							Cards.FromName("Witchwood Grizzly"),
						}
						),
				new Deck(
						"Silence_Priest3",
						610,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Silence"),
							Cards.FromName("Silence"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Ancient Watcher"),
							Cards.FromName("Ancient Watcher"),
							Cards.FromName("Dalaran Librarian"),
							Cards.FromName("Dalaran Librarian"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Arcane Watcher"),
							Cards.FromName("Arcane Watcher"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Madame Lazul"),
							Cards.FromName("Auchenai Soulpriest"),
							Cards.FromName("Hench-Clan Shadequill"),
							Cards.FromName("Hench-Clan Shadequill"),
							Cards.FromName("Unsleeping Soul"),
							Cards.FromName("Unsleeping Soul"),
						}
						),
				new Deck(
						"Silence_Priest4",
						610,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Silence"),
							Cards.FromName("Silence"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Ancient Watcher"),
							Cards.FromName("Ancient Watcher"),
							Cards.FromName("Dalaran Librarian"),
							Cards.FromName("Dalaran Librarian"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Arcane Watcher"),
							Cards.FromName("Arcane Watcher"),
							Cards.FromName("Faceless Rager"),
							Cards.FromName("Faceless Rager"),
							Cards.FromName("Hench-Clan Shadequill"),
							Cards.FromName("Hench-Clan Shadequill"),
							Cards.FromName("Unsleeping Soul"),
							Cards.FromName("Unsleeping Soul"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Witchwood Grizzly"),
						}
						),
				new Deck(
						"Combo_Priest8",
						600,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Activate the Obelisk"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Stonetusk Boar"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Wild Pyromancer"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("High Priest Amet"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Sandhoof Waterbearer"),
						}
						),
				new Deck(
						"Resurrect_Priest7",
						580,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Topsy Turvy"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Shadow Word: Pain"),
							Cards.FromName("Shadow Word: Pain"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Auchenai Soulpriest"),
							Cards.FromName("Auchenai Soulpriest"),
							Cards.FromName("Hench-Clan Shadequill"),
							Cards.FromName("Hench-Clan Shadequill"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Batterhead"),
							Cards.FromName("Catrina Muerte"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Mass Resurrection"),
						}
						),
				new Deck(
						"Resurrect_Priest8",
						500,
						new List<Card>
						{
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Activate the Obelisk"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Penance"),
							Cards.FromName("Penance"),
							Cards.FromName("Shadow Word: Pain"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Bone Wraith"),
							Cards.FromName("Bone Wraith"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Catrina Muerte"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Plague of Death"),
							Cards.FromName("Plague of Death"),
							Cards.FromName("King Phaoris"),
						}
						),
				new Deck(
						"Resurrect_Priest9",
						500,
						new List<Card>
						{
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Inner Fire"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Divine Spirit"),
							Cards.FromName("Seance"),
							Cards.FromName("Seance"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Holy Nova"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Catrina Muerte"),
							Cards.FromName("Mosh'Ogg Enforcer"),
							Cards.FromName("Mosh'Ogg Enforcer"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Mass Resurrection"),
						}
						),
				new Deck(
						"Priest4",
						440,
						new List<Card>
						{
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Circle of Healing"),
							Cards.FromName("Silence"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Auchenai Phantasm"),
							Cards.FromName("Auchenai Phantasm"),
							Cards.FromName("Dead Ringer"),
							Cards.FromName("Dead Ringer"),
							Cards.FromName("EVIL Conscripter"),
							Cards.FromName("EVIL Conscripter"),
							Cards.FromName("Extra Arms"),
							Cards.FromName("Shadowy Figure"),
							Cards.FromName("Shadowy Figure"),
							Cards.FromName("Madame Lazul"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Auchenai Soulpriest"),
							Cards.FromName("Auchenai Soulpriest"),
							Cards.FromName("Hench-Clan Shadequill"),
							Cards.FromName("Hench-Clan Shadequill"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Coffin Crasher"),
							Cards.FromName("Coffin Crasher"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Da Undatakah"),
						}
						),
				new Deck(
						"Quest_Priest7",
						440,
						new List<Card>
						{
							Cards.FromName("Activate the Obelisk"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Northshire Cleric"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Holy Ripple"),
							Cards.FromName("Holy Ripple"),
							Cards.FromName("Penance"),
							Cards.FromName("Penance"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("High Priest Amet"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Siamat"),
							Cards.FromName("Catrina Muerte"),
							Cards.FromName("Mosh'Ogg Enforcer"),
							Cards.FromName("Mosh'Ogg Enforcer"),
							Cards.FromName("Archivist Elysiana"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Plague of Death"),
							Cards.FromName("Plague of Death"),
						}
						),
				new Deck(
						"Resurrect_Priest10",
						420,
						new List<Card>
						{
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Penance"),
							Cards.FromName("Penance"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Mass Dispel"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Damaged Stegotron"),
							Cards.FromName("Catrina Muerte"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Mass Resurrection"),
						}
						),
				new Deck(
						"Quest_Priest8",
						410,
						new List<Card>
						{
							Cards.FromName("Forbidden Words"),
							Cards.FromName("Activate the Obelisk"),
							Cards.FromName("Holy Smite"),
							Cards.FromName("Power Word: Shield"),
							Cards.FromName("Divine Hymn"),
							Cards.FromName("Holy Ripple"),
							Cards.FromName("Penance"),
							Cards.FromName("Shadow Word: Pain"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Injured Blademaster"),
							Cards.FromName("Shadow Word: Death"),
							Cards.FromName("Archmage Vargoth"),
							Cards.FromName("Hench-Clan Shadequill"),
							Cards.FromName("High Priest Amet"),
							Cards.FromName("Psychopomp"),
							Cards.FromName("Convincing Infiltrator"),
							Cards.FromName("Mass Hysteria"),
							Cards.FromName("Rotten Applebaum"),
							Cards.FromName("Sandhoof Waterbearer"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Cairne Bloodhoof"),
							Cards.FromName("Holy Fire"),
							Cards.FromName("Khartut Defender"),
							Cards.FromName("Catrina Muerte"),
							Cards.FromName("Mass Resurrection"),
							Cards.FromName("Plague of Death"),
							Cards.FromName("Zerek's Cloning Gallery"),
							Cards.FromName("Colossus of the Moon"),
							Cards.FromName("King Phaoris"),
							Cards.FromName("Mind Control"),
						}
						)
				};
		}
	}
}