using System.Collections.Generic;
using SabberStoneCore.Model;
using SabberStoneCore.Enums;

namespace SabberStoneCoreAi.Meta
{
	public class ROGUEDecks
	{
		public List<Deck> decks;

		public ROGUEDecks()
		{
			decks = new List<Deck> {
				new Deck(CardClass.ROGUE,
						"Quest_Rogue1",
						16000,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Tess Greymane"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue1",
						7900,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Faerie Dragon"),
							Cards.FromName("Faerie Dragon"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Hooked Scimitar"),
							Cards.FromName("Hooked Scimitar"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Captain Greenskin"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Myra's Unstable Element"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue2",
						7700,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Myra's Unstable Element"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Thief_Rogue1",
						7500,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Academic Espionage"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Raiding Party"),
							Cards.FromName("Spectral Cutlass"),
							Cards.FromName("Spectral Cutlass"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Captain Greenskin"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Gadgetzan Auctioneer"),
							Cards.FromName("Gadgetzan Auctioneer"),
							Cards.FromName("Tess Greymane"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue3",
						7200,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Hooktusk_Rogue1",
						5300,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Captain Hooktusk"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Quest_Rogue2",
						4900,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Tess Greymane"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Quest_Rogue3",
						4600,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue4",
						4500,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Quest_Rogue4",
						4300,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Tess Greymane"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue5",
						3500,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Rogue1",
						2600,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Faerie Dragon"),
							Cards.FromName("Faerie Dragon"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Hench-Clan Thug"),
							Cards.FromName("Hench-Clan Thug"),
							Cards.FromName("Hooked Scimitar"),
							Cards.FromName("Hooked Scimitar"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Captain Greenskin"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Myra's Unstable Element"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Quest_Rogue5",
						2500,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Blade Flurry"),
							Cards.FromName("Blade Flurry"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Tess Greymane"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Quest_Rogue6",
						2400,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Togwaggle's Scheme"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Brightwing"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Blade Flurry"),
							Cards.FromName("Blade Flurry"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Tess Greymane"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue6",
						2100,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Quest_Rogue7",
						2000,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Sahket Sapper"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Cursed Castaway"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Siamat"),
							Cards.FromName("Captain Hooktusk"),
							Cards.FromName("Tess Greymane"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue7",
						2000,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Sap"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("Hench-Clan Thug"),
							Cards.FromName("Hench-Clan Thug"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Walk the Plank"),
							Cards.FromName("Walk the Plank"),
							Cards.FromName("Myra's Unstable Element"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Chef Nomi"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue8",
						2000,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Quest_Rogue8",
						1800,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Togwaggle's Scheme"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Face Collector"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Blade Flurry"),
							Cards.FromName("Blade Flurry"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Tess Greymane"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Quest_Rogue9",
						1700,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Blade Flurry"),
							Cards.FromName("Blade Flurry"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue9",
						1600,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue10",
						1500,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Myra's Unstable Element"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Chef Nomi"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue11",
						1500,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Faerie Dragon"),
							Cards.FromName("Faerie Dragon"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Raiding Party"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Myra's Unstable Element"),
							Cards.FromName("Chef Nomi"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Hooktusk_Rogue2",
						1500,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Captain Hooktusk"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue12",
						1400,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue13",
						1400,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Sinister Strike"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Faerie Dragon"),
							Cards.FromName("Faerie Dragon"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Raiding Party"),
							Cards.FromName("Raiding Party"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Captain Greenskin"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Myra's Unstable Element"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Quest_Rogue10",
						1300,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Pogo_Rogue1",
						1300,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Pogo-Hopper"),
							Cards.FromName("Pogo-Hopper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Lab Recruiter"),
							Cards.FromName("Lab Recruiter"),
							Cards.FromName("Loot Hoarder"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Shiv"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Witchwood Piper"),
							Cards.FromName("Witchwood Piper"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Myra's Unstable Element"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue14",
						1300,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Sea Giant"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Quest_Rogue11",
						1200,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Tess Greymane"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Hooktusk_Rogue3",
						1100,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Serrated Tooth"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Southsea Captain"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Captain Greenskin"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Captain Hooktusk"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Hooktusk_Rogue4",
						1000,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Captain Hooktusk"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Quest_Rogue12",
						1000,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue15",
						1000,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Pogo_Rogue2",
						930,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Pogo-Hopper"),
							Cards.FromName("Pogo-Hopper"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Lab Recruiter"),
							Cards.FromName("Lab Recruiter"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Shiv"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Witchwood Piper"),
							Cards.FromName("Witchwood Piper"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Myra's Unstable Element"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Quest_Rogue13",
						890,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Blade Flurry"),
							Cards.FromName("Blade Flurry"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Tess Greymane"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Hooktusk_Rogue5",
						880,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Captain Hooktusk"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue16",
						870,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Hench-Clan Thug"),
							Cards.FromName("Hench-Clan Thug"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Raiding Party"),
							Cards.FromName("Raiding Party"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Captain Greenskin"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Myra's Unstable Element"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue17",
						860,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Myra's Unstable Element"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Chef Nomi"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Hooktusk_Rogue6",
						770,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Cursed Castaway"),
							Cards.FromName("Cursed Castaway"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Captain Hooktusk"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Pogo_Rogue3",
						740,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Pogo-Hopper"),
							Cards.FromName("Pogo-Hopper"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Lab Recruiter"),
							Cards.FromName("Lab Recruiter"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Shiv"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Witchwood Piper"),
							Cards.FromName("Witchwood Piper"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Myra's Unstable Element"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Rogue2",
						700,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Necrium Blade"),
							Cards.FromName("Necrium Blade"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Blightnozzle Crawler"),
							Cards.FromName("Blightnozzle Crawler"),
							Cards.FromName("Bone Wraith"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Anka, the Buried"),
							Cards.FromName("Necrium Vial"),
							Cards.FromName("Necrium Vial"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Cairne Bloodhoof"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Mechanical Whelp"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Quest_Rogue14",
						700,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("Blade Flurry"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue18",
						700,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Raiding Party"),
							Cards.FromName("Raiding Party"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Captain Greenskin"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Myra's Unstable Element"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue19",
						690,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Myra's Unstable Element"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Chef Nomi"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue20",
						660,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Pilfer"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue21",
						650,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Thief_Rogue2",
						650,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Togwaggle's Scheme"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Raiding Party"),
							Cards.FromName("Spectral Cutlass"),
							Cards.FromName("Spectral Cutlass"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Captain Greenskin"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Gadgetzan Auctioneer"),
							Cards.FromName("Gadgetzan Auctioneer"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Tess Greymane"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Hooktusk_Rogue7",
						650,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Bloodsail Raider"),
							Cards.FromName("Bloodsail Raider"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Hench-Clan Thug"),
							Cards.FromName("Hooked Scimitar"),
							Cards.FromName("Hooked Scimitar"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Southsea Captain"),
							Cards.FromName("Southsea Captain"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Raiding Party"),
							Cards.FromName("Raiding Party"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Captain Greenskin"),
							Cards.FromName("Cannon Barrage"),
							Cards.FromName("Cursed Castaway"),
							Cards.FromName("Cursed Castaway"),
							Cards.FromName("Captain Hooktusk"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue22",
						640,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Pilfer"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Quest_Rogue15",
						630,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Tess Greymane"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue23",
						590,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Drakkari Trickster"),
							Cards.FromName("Drakkari Trickster"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Tanglefur Mystic"),
							Cards.FromName("Tanglefur Mystic"),
							Cards.FromName("Griftah"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Hooktusk_Rogue8",
						540,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Cursed Castaway"),
							Cards.FromName("Cursed Castaway"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Captain Hooktusk"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Hooktusk_Rogue9",
						540,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Hench-Clan Thug"),
							Cards.FromName("Hench-Clan Thug"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Dalaran Crusader"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Cursed Castaway"),
							Cards.FromName("Cursed Castaway"),
							Cards.FromName("Captain Hooktusk"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue24",
						540,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Rogue3",
						540,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Togwaggle's Scheme"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Face Collector"),
							Cards.FromName("Blade Flurry"),
							Cards.FromName("Blade Flurry"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Gadgetzan Auctioneer"),
							Cards.FromName("Gadgetzan Auctioneer"),
							Cards.FromName("Tess Greymane"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue25",
						540,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Defias Ringleader"),
							Cards.FromName("Defias Ringleader"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Sharkfin Fan"),
							Cards.FromName("Sharkfin Fan"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Hench-Clan Thug"),
							Cards.FromName("Hench-Clan Thug"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Thief_Rogue3",
						530,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Togwaggle's Scheme"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Raiding Party"),
							Cards.FromName("Spectral Cutlass"),
							Cards.FromName("Spectral Cutlass"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Captain Greenskin"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Gadgetzan Auctioneer"),
							Cards.FromName("Gadgetzan Auctioneer"),
							Cards.FromName("Tess Greymane"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Tempo_Rogue26",
						500,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Sinister Strike"),
							Cards.FromName("Sinister Strike"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Faerie Dragon"),
							Cards.FromName("Faerie Dragon"),
							Cards.FromName("Sap"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Raiding Party"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Waggle Pick"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Myra's Unstable Element"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Quest_Rogue16",
						490,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Tess Greymane"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Quest_Rogue17",
						490,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Togwaggle's Scheme"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Blade Flurry"),
							Cards.FromName("Blade Flurry"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Tess Greymane"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Rogue4",
						470,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pharaoh Cat"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Doomsayer"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Pick Pocket"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Sandbinder"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Bazaar Mugger"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Siamat"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Thief_Rogue4",
						470,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Deadly Poison"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Togwaggle's Scheme"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Academic Espionage"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Raiding Party"),
							Cards.FromName("Spectral Cutlass"),
							Cards.FromName("Spectral Cutlass"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Captain Greenskin"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Gadgetzan Auctioneer"),
							Cards.FromName("Gadgetzan Auctioneer"),
							Cards.FromName("Tess Greymane"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Quest_Rogue18",
						470,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Bazaar Burglary"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Pilfer"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("Clever Disguise"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Underbelly Fence"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Blink Fox"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Blade Flurry"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Vendetta"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Hooktusk_Rogue10",
						440,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Southsea Deckhand"),
							Cards.FromName("Bloodsail Raider"),
							Cards.FromName("Bloodsail Raider"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Sharkfin Fan"),
							Cards.FromName("Sharkfin Fan"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("Hench-Clan Thug"),
							Cards.FromName("Hench-Clan Thug"),
							Cards.FromName("SI:7 Agent"),
							Cards.FromName("Southsea Captain"),
							Cards.FromName("Southsea Captain"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Hench-Clan Burglar"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Ticket Scalper"),
							Cards.FromName("Walk the Plank"),
							Cards.FromName("Captain Greenskin"),
							Cards.FromName("Cannon Barrage"),
							Cards.FromName("Cursed Castaway"),
							Cards.FromName("Cursed Castaway"),
							Cards.FromName("Captain Hooktusk"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Rogue5",
						430,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Eviscerate"),
							Cards.FromName("Sap"),
							Cards.FromName("Sap"),
							Cards.FromName("Shiv"),
							Cards.FromName("Shiv"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("Necrium Blade"),
							Cards.FromName("Necrium Blade"),
							Cards.FromName("Shadow of Death"),
							Cards.FromName("Shadow of Death"),
							Cards.FromName("Witchwood Piper"),
							Cards.FromName("Witchwood Piper"),
							Cards.FromName("Anka, the Buried"),
							Cards.FromName("Necrium Vial"),
							Cards.FromName("Cairne Bloodhoof"),
							Cards.FromName("Khartut Defender"),
							Cards.FromName("Khartut Defender"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Deranged Doctor"),
							Cards.FromName("Octosari"),
							Cards.FromName("Anubisath Warbringer"),
							Cards.FromName("Anubisath Warbringer"),
						}
						),
				new Deck(CardClass.ROGUE,
						"Pogo_Rogue4",
						410,
						new List<Card>
						{
							Cards.FromName("Backstab"),
							Cards.FromName("Backstab"),
							Cards.FromName("Preparation"),
							Cards.FromName("Preparation"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Shadowstep"),
							Cards.FromName("Pogo-Hopper"),
							Cards.FromName("Pogo-Hopper"),
							Cards.FromName("Bloodmage Thalnos"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Lab Recruiter"),
							Cards.FromName("Lab Recruiter"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Sap"),
							Cards.FromName("Shiv"),
							Cards.FromName("Shiv"),
							Cards.FromName("Edwin VanCleef"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("EVIL Miscreant"),
							Cards.FromName("Fan of Knives"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Spirit of the Shark"),
							Cards.FromName("Witchwood Piper"),
							Cards.FromName("Witchwood Piper"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Heistbaron Togwaggle"),
							Cards.FromName("Jepetto Joybuzz"),
						}
						)
				};
		}
	}
}
