using System.Collections.Generic;
using SabberStoneCore.Model;

namespace SabberStoneCoreAi.Meta
{
	public class WARLOCKDecks
	{
		public List<Deck> decks;

		public WARLOCKDecks()
		{
			decks = new List<Deck> {
				new Deck(
						"Zoo_Warlock1",
						6700,
						new List<Card>
						{
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Dark Pharaoh Tekahn"),
							Cards.FromName("Leeroy Jenkins"),
						}
						),
				new Deck(
						"Zoo_Warlock2",
						5300,
						new List<Card>
						{
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Defender of Argus"),
							Cards.FromName("Defender of Argus"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Sea Giant"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Zoo_Warlock3",
						4500,
						new List<Card>
						{
							Cards.FromName("Beaming Sidekick"),
							Cards.FromName("Beaming Sidekick"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Spirit Bomb"),
							Cards.FromName("Spirit Bomb"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Nethersoul Buster"),
							Cards.FromName("Nethersoul Buster"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Dark Pharaoh Tekahn"),
						}
						),
				new Deck(
						"Zoo_Warlock4",
						3500,
						new List<Card>
						{
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Saronite Taskmaster"),
							Cards.FromName("Saronite Taskmaster"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Arch-Villain Rafaam"),
							Cards.FromName("Sea Giant"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Zoo_Warlock5",
						3000,
						new List<Card>
						{
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Spirit Bomb"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Diseased Vulture"),
						}
						),
				new Deck(
						"Zoo_Warlock6",
						2900,
						new List<Card>
						{
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Soulfire"),
							Cards.FromName("Soulfire"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Zoo_Warlock7",
						2800,
						new List<Card>
						{
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mortal Coil"),
							Cards.FromName("Mortal Coil"),
							Cards.FromName("Plague of Flames"),
							Cards.FromName("Plague of Flames"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Cult Master"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Dark Pharaoh Tekahn"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Mecha'thun"),
						}
						),
				new Deck(
						"Quest_Warlock1",
						2400,
						new List<Card>
						{
							Cards.FromName("Mortal Coil"),
							Cards.FromName("Mortal Coil"),
							Cards.FromName("Supreme Archaeology"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Plot Twist"),
							Cards.FromName("Plot Twist"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Shadow Bolt"),
							Cards.FromName("Bone Wraith"),
							Cards.FromName("Bone Wraith"),
							Cards.FromName("Hellfire"),
							Cards.FromName("Impbalming"),
							Cards.FromName("Impbalming"),
							Cards.FromName("Dollmaster Dorian"),
							Cards.FromName("Rotten Applebaum"),
							Cards.FromName("Rotten Applebaum"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Aranasi Broodmother"),
							Cards.FromName("Aranasi Broodmother"),
							Cards.FromName("Dr. Morrigan"),
							Cards.FromName("Khartut Defender"),
							Cards.FromName("Khartut Defender"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Arch-Villain Rafaam"),
							Cards.FromName("Lord Godfrey"),
							Cards.FromName("Fel Lord Betrug"),
							Cards.FromName("Twisting Nether"),
						}
						),
				new Deck(
						"Zoo_Warlock8",
						2100,
						new List<Card>
						{
							Cards.FromName("Beaming Sidekick"),
							Cards.FromName("Beaming Sidekick"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Soulfire"),
							Cards.FromName("Soulfire"),
							Cards.FromName("Spirit Bomb"),
							Cards.FromName("Spirit Bomb"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Leeroy Jenkins"),
						}
						),
				new Deck(
						"Mech_Zoo_Warlock1",
						2100,
						new List<Card>
						{
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Soulfire"),
							Cards.FromName("Soulfire"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Defender of Argus"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
						}
						),
				new Deck(
						"Zoo_Warlock9",
						1900,
						new List<Card>
						{
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Soulfire"),
							Cards.FromName("Soulfire"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Lost Spirit"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Sea Giant"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Zoo_Warlock10",
						1700,
						new List<Card>
						{
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Soulfire"),
							Cards.FromName("Soulfire"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Diseased Vulture"),
						}
						),
				new Deck(
						"Mech_Zoo_Warlock2",
						1700,
						new List<Card>
						{
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Soulfire"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Whirliglider"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Wargear"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Sea Giant"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Zoo_Warlock11",
						1600,
						new List<Card>
						{
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Defender of Argus"),
							Cards.FromName("Defender of Argus"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Leeroy Jenkins"),
						}
						),
				new Deck(
						"Plot_Twist_Warlock1",
						1400,
						new List<Card>
						{
							Cards.FromName("Mortal Coil"),
							Cards.FromName("Mortal Coil"),
							Cards.FromName("Plot Twist"),
							Cards.FromName("Plot Twist"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Shadow Bolt"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Hellfire"),
							Cards.FromName("Hellfire"),
							Cards.FromName("Shadowflame"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Dollmaster Dorian"),
							Cards.FromName("Rotten Applebaum"),
							Cards.FromName("Rotten Applebaum"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Aranasi Broodmother"),
							Cards.FromName("Aranasi Broodmother"),
							Cards.FromName("Dr. Morrigan"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Safeguard"),
							Cards.FromName("Safeguard"),
							Cards.FromName("Siphon Soul"),
							Cards.FromName("Lord Godfrey"),
							Cards.FromName("Deranged Doctor"),
							Cards.FromName("Fel Lord Betrug"),
							Cards.FromName("Twisting Nether"),
							Cards.FromName("Mountain Giant"),
							Cards.FromName("Mountain Giant"),
						}
						),
				new Deck(
						"Quest_Warlock2",
						1300,
						new List<Card>
						{
							Cards.FromName("Mortal Coil"),
							Cards.FromName("Supreme Archaeology"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Injured Tol'vir"),
							Cards.FromName("Plot Twist"),
							Cards.FromName("Plot Twist"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Earthen Ring Farseer"),
							Cards.FromName("Earthen Ring Farseer"),
							Cards.FromName("Hellfire"),
							Cards.FromName("Hellfire"),
							Cards.FromName("Proud Defender"),
							Cards.FromName("Proud Defender"),
							Cards.FromName("Dollmaster Dorian"),
							Cards.FromName("Rotten Applebaum"),
							Cards.FromName("Rotten Applebaum"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Aranasi Broodmother"),
							Cards.FromName("Aranasi Broodmother"),
							Cards.FromName("Khartut Defender"),
							Cards.FromName("Khartut Defender"),
							Cards.FromName("Siphon Soul"),
							Cards.FromName("Arch-Villain Rafaam"),
							Cards.FromName("Lord Godfrey"),
							Cards.FromName("Fel Lord Betrug"),
							Cards.FromName("Twisting Nether"),
						}
						),
				new Deck(
						"Zoo_Warlock12",
						1200,
						new List<Card>
						{
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Plague of Flames"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Dark Pharaoh Tekahn"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Sea Giant"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Zoo_Warlock13",
						1200,
						new List<Card>
						{
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Saronite Taskmaster"),
							Cards.FromName("Saronite Taskmaster"),
							Cards.FromName("Soulfire"),
							Cards.FromName("Soulfire"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Crazed Alchemist"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Zoo_Warlock14",
						1200,
						new List<Card>
						{
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Saronite Taskmaster"),
							Cards.FromName("Saronite Taskmaster"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Sea Giant"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Zoo_Warlock15",
						1100,
						new List<Card>
						{
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Jar Dealer"),
							Cards.FromName("Jar Dealer"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Leeroy Jenkins"),
						}
						),
				new Deck(
						"Handlock1",
						1000,
						new List<Card>
						{
							Cards.FromName("Mortal Coil"),
							Cards.FromName("Mortal Coil"),
							Cards.FromName("Shriek"),
							Cards.FromName("Shriek"),
							Cards.FromName("Doomsayer"),
							Cards.FromName("Doomsayer"),
							Cards.FromName("Plot Twist"),
							Cards.FromName("Sunfury Protector"),
							Cards.FromName("Sunfury Protector"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Hellfire"),
							Cards.FromName("Hellfire"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Omega Agent"),
							Cards.FromName("Rotten Applebaum"),
							Cards.FromName("Rotten Applebaum"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Aranasi Broodmother"),
							Cards.FromName("Aranasi Broodmother"),
							Cards.FromName("Siphon Soul"),
							Cards.FromName("Siphon Soul"),
							Cards.FromName("Arch-Villain Rafaam"),
							Cards.FromName("Lord Godfrey"),
							Cards.FromName("Lord Jaraxxus"),
							Cards.FromName("Mountain Giant"),
							Cards.FromName("Mountain Giant"),
						}
						),
				new Deck(
						"Plot_Twist_Warlock2",
						1000,
						new List<Card>
						{
							Cards.FromName("Mortal Coil"),
							Cards.FromName("Mortal Coil"),
							Cards.FromName("Shriek"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Plot Twist"),
							Cards.FromName("Plot Twist"),
							Cards.FromName("Earthen Ring Farseer"),
							Cards.FromName("Shadow Bolt"),
							Cards.FromName("Shadow Bolt"),
							Cards.FromName("Hellfire"),
							Cards.FromName("Hellfire"),
							Cards.FromName("Proud Defender"),
							Cards.FromName("Proud Defender"),
							Cards.FromName("Dollmaster Dorian"),
							Cards.FromName("Rotten Applebaum"),
							Cards.FromName("Rotten Applebaum"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Aranasi Broodmother"),
							Cards.FromName("Aranasi Broodmother"),
							Cards.FromName("Dr. Morrigan"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Siphon Soul"),
							Cards.FromName("Siphon Soul"),
							Cards.FromName("Arch-Villain Rafaam"),
							Cards.FromName("Lord Godfrey"),
							Cards.FromName("Batterhead"),
							Cards.FromName("Batterhead"),
							Cards.FromName("Fel Lord Betrug"),
							Cards.FromName("Twisting Nether"),
						}
						),
				new Deck(
						"Warlock1",
						1000,
						new List<Card>
						{
							Cards.FromName("Plague of Flames"),
							Cards.FromName("Plague of Flames"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Supreme Archaeology"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Galvanizer"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Plot Twist"),
							Cards.FromName("Plot Twist"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Hellfire"),
							Cards.FromName("Hellfire"),
							Cards.FromName("Dark Pharaoh Tekahn"),
							Cards.FromName("Dollmaster Dorian"),
							Cards.FromName("Rotten Applebaum"),
							Cards.FromName("Rotten Applebaum"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Aranasi Broodmother"),
							Cards.FromName("Aranasi Broodmother"),
							Cards.FromName("Khartut Defender"),
							Cards.FromName("Khartut Defender"),
							Cards.FromName("Lord Godfrey"),
							Cards.FromName("Fel Lord Betrug"),
							Cards.FromName("Twisting Nether"),
							Cards.FromName("Mecha'thun"),
						}
						),
				new Deck(
						"Warlock2",
						1000,
						new List<Card>
						{
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Riftcleaver"),
							Cards.FromName("Demonbolt"),
						}
						),
				new Deck(
						"Zoo_Warlock16",
						960,
						new List<Card>
						{
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Witchwood Imp"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Sea Giant"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Quest_Warlock3",
						860,
						new List<Card>
						{
							Cards.FromName("Mortal Coil"),
							Cards.FromName("Mortal Coil"),
							Cards.FromName("Supreme Archaeology"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Plot Twist"),
							Cards.FromName("Plot Twist"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Sense Demons"),
							Cards.FromName("Shadow Bolt"),
							Cards.FromName("Shadow Bolt"),
							Cards.FromName("Proud Defender"),
							Cards.FromName("Proud Defender"),
							Cards.FromName("Dollmaster Dorian"),
							Cards.FromName("Rotten Applebaum"),
							Cards.FromName("Rotten Applebaum"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Aranasi Broodmother"),
							Cards.FromName("Aranasi Broodmother"),
							Cards.FromName("Dr. Morrigan"),
							Cards.FromName("Khartut Defender"),
							Cards.FromName("Khartut Defender"),
							Cards.FromName("Riftcleaver"),
							Cards.FromName("Riftcleaver"),
							Cards.FromName("Siphon Soul"),
							Cards.FromName("Arch-Villain Rafaam"),
							Cards.FromName("Lord Godfrey"),
							Cards.FromName("Fel Lord Betrug"),
							Cards.FromName("Twisting Nether"),
							Cards.FromName("Hakkar, the Soulflayer"),
						}
						),
				new Deck(
						"Zoo_Warlock17",
						860,
						new List<Card>
						{
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Elven Archer"),
							Cards.FromName("Elven Archer"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Dark Pharaoh Tekahn"),
						}
						),
				new Deck(
						"Zoo_Warlock18",
						840,
						new List<Card>
						{
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Soulfire"),
							Cards.FromName("Soulfire"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Witchwood Imp"),
							Cards.FromName("Witchwood Imp"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Dark Pharaoh Tekahn"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
						}
						),
				new Deck(
						"Zoo_Warlock19",
						810,
						new List<Card>
						{
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Spirit Bomb"),
							Cards.FromName("Spirit Bomb"),
							Cards.FromName("The Soularium"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Duskbat"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Nethersoul Buster"),
							Cards.FromName("Nethersoul Buster"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Demonbolt"),
							Cards.FromName("Demonbolt"),
							Cards.FromName("Sea Giant"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Zoo_Warlock20",
						810,
						new List<Card>
						{
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Soulfire"),
							Cards.FromName("Soulfire"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Impbalming"),
							Cards.FromName("Dark Pharaoh Tekahn"),
						}
						),
				new Deck(
						"Zoo_Warlock21",
						800,
						new List<Card>
						{
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Witchwood Imp"),
							Cards.FromName("Witchwood Imp"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Arch-Villain Rafaam"),
							Cards.FromName("Sea Giant"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Handlock2",
						780,
						new List<Card>
						{
							Cards.FromName("Mortal Coil"),
							Cards.FromName("Mortal Coil"),
							Cards.FromName("Acidic Swamp Ooze"),
							Cards.FromName("Doomsayer"),
							Cards.FromName("Doomsayer"),
							Cards.FromName("Sunfury Protector"),
							Cards.FromName("Sunfury Protector"),
							Cards.FromName("Earthen Ring Farseer"),
							Cards.FromName("Earthen Ring Farseer"),
							Cards.FromName("Shadow Bolt"),
							Cards.FromName("Hellfire"),
							Cards.FromName("Hellfire"),
							Cards.FromName("Proud Defender"),
							Cards.FromName("Proud Defender"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Omega Agent"),
							Cards.FromName("Omega Agent"),
							Cards.FromName("Rotten Applebaum"),
							Cards.FromName("Rotten Applebaum"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Siphon Soul"),
							Cards.FromName("Siphon Soul"),
							Cards.FromName("Arch-Villain Rafaam"),
							Cards.FromName("Lord Godfrey"),
							Cards.FromName("Twisting Nether"),
							Cards.FromName("Mountain Giant"),
							Cards.FromName("Mountain Giant"),
						}
						),
				new Deck(
						"Zoo_Warlock22",
						720,
						new List<Card>
						{
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Witchwood Imp"),
							Cards.FromName("Witchwood Imp"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Sea Giant"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Zoo_Warlock23",
						700,
						new List<Card>
						{
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Void Terror"),
							Cards.FromName("Void Terror"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Dark Pharaoh Tekahn"),
						}
						),
				new Deck(
						"Mech_Zoo_Warlock3",
						640,
						new List<Card>
						{
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Soulfire"),
							Cards.FromName("Soulfire"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Harvest Golem"),
							Cards.FromName("Harvest Golem"),
							Cards.FromName("Defender of Argus"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Explodinator"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Frostwolf Warlord"),
							Cards.FromName("Frostwolf Warlord"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
						}
						),
				new Deck(
						"Zoo_Warlock24",
						550,
						new List<Card>
						{
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Soulfire"),
							Cards.FromName("Soulfire"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Witchwood Imp"),
							Cards.FromName("Witchwood Imp"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Doubling Imp"),
							Cards.FromName("Doubling Imp"),
							Cards.FromName("Impferno"),
							Cards.FromName("Impferno"),
							Cards.FromName("Rafaam's Scheme"),
							Cards.FromName("Rafaam's Scheme"),
							Cards.FromName("Fiendish Circle"),
							Cards.FromName("Fiendish Circle"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Jumbo Imp"),
							Cards.FromName("Jumbo Imp"),
							Cards.FromName("Sea Giant"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Zoo_Warlock25",
						540,
						new List<Card>
						{
							Cards.FromName("Blood Imp"),
							Cards.FromName("Blood Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Soulfire"),
							Cards.FromName("Soulfire"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Witchwood Imp"),
							Cards.FromName("Witchwood Imp"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Void Analyst"),
							Cards.FromName("Void Analyst"),
							Cards.FromName("Doubling Imp"),
							Cards.FromName("Doubling Imp"),
							Cards.FromName("Impferno"),
							Cards.FromName("Impferno"),
							Cards.FromName("Rafaam's Scheme"),
							Cards.FromName("Rafaam's Scheme"),
							Cards.FromName("Fiendish Circle"),
							Cards.FromName("Fiendish Circle"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Jumbo Imp"),
							Cards.FromName("Jumbo Imp"),
							Cards.FromName("Sea Giant"),
							Cards.FromName("Sea Giant"),
						}
						),
				new Deck(
						"Warlock3",
						490,
						new List<Card>
						{
							Cards.FromName("Mortal Coil"),
							Cards.FromName("Mortal Coil"),
							Cards.FromName("Plague of Flames"),
							Cards.FromName("Supreme Archaeology"),
							Cards.FromName("Plot Twist"),
							Cards.FromName("Plot Twist"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Rafaam's Scheme"),
							Cards.FromName("Rafaam's Scheme"),
							Cards.FromName("Fiendish Circle"),
							Cards.FromName("Hellfire"),
							Cards.FromName("Dollmaster Dorian"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Aranasi Broodmother"),
							Cards.FromName("Aranasi Broodmother"),
							Cards.FromName("Darkest Hour"),
							Cards.FromName("Dr. Morrigan"),
							Cards.FromName("Khartut Defender"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Mechanical Whelp"),
							Cards.FromName("Safeguard"),
							Cards.FromName("Arch-Villain Rafaam"),
							Cards.FromName("Lord Godfrey"),
							Cards.FromName("Fel Lord Betrug"),
							Cards.FromName("Twisting Nether"),
							Cards.FromName("Colossus of the Moon"),
							Cards.FromName("Mountain Giant"),
							Cards.FromName("Mountain Giant"),
						}
						),
				new Deck(
						"Mech_Zoo_Warlock4",
						440,
						new List<Card>
						{
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Argent Squire"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("Mecharoo"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Scarab Egg"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Replicating Menace"),
							Cards.FromName("Wargear"),
							Cards.FromName("Wargear"),
						}
						),
				new Deck(
						"Zoo_Warlock26",
						420,
						new List<Card>
						{
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Abusive Sergeant"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Crystallizer"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Flame Imp"),
							Cards.FromName("Grim Rally"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("Sinister Deal"),
							Cards.FromName("The Soularium"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Voidwalker"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("Dire Wolf Alpha"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("EVIL Genius"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("Serpent Egg"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("EVIL Recruiter"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Magic Carpet"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Neferset Thrasher"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Diseased Vulture"),
							Cards.FromName("Dark Pharaoh Tekahn"),
							Cards.FromName("Leeroy Jenkins"),
						}
						)
				};
		}
	}
}