using System.Collections.Generic;
using SabberStoneCore.Model;

namespace SabberStoneCoreAi.Meta
{
	public class WARRIORDecks
	{
		public List<Deck> decks;

		public WARRIORDecks()
		{
			decks = new List<Deck> {
				new Deck(
						"Control_Warrior1",
						46000,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Plague of Wrath"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Armagedillo"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior2",
						45000,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Bomb_Warrior1",
						14000,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
						}
						),
				new Deck(
						"Control_Warrior3",
						10000,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Armagedillo"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Bomb_Warrior2",
						5900,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Aggro_Warrior1",
						4700,
						new List<Card>
						{
							Cards.FromName("Inner Rage"),
							Cards.FromName("Inner Rage"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Amani Berserker"),
							Cards.FromName("Amani Berserker"),
							Cards.FromName("Battle Rage"),
							Cards.FromName("Battle Rage"),
							Cards.FromName("Cruel Taskmaster"),
							Cards.FromName("Cruel Taskmaster"),
							Cards.FromName("Temple Berserker"),
							Cards.FromName("Temple Berserker"),
							Cards.FromName("Bloodsworn Mercenary"),
							Cards.FromName("Bloodsworn Mercenary"),
							Cards.FromName("Frothing Berserker"),
							Cards.FromName("Frothing Berserker"),
							Cards.FromName("Livewire Lance"),
							Cards.FromName("Livewire Lance"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Kor'kron Elite"),
							Cards.FromName("Kor'kron Elite"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Grommash Hellscream"),
						}
						),
				new Deck(
						"Bomb_Warrior3",
						4100,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Bomb_Warrior4",
						3900,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Aggro_Warrior2",
						3500,
						new List<Card>
						{
							Cards.FromName("Inner Rage"),
							Cards.FromName("Inner Rage"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Battle Rage"),
							Cards.FromName("Battle Rage"),
							Cards.FromName("Cruel Taskmaster"),
							Cards.FromName("Cruel Taskmaster"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Temple Berserker"),
							Cards.FromName("Temple Berserker"),
							Cards.FromName("Bloodsworn Mercenary"),
							Cards.FromName("Bloodsworn Mercenary"),
							Cards.FromName("Frothing Berserker"),
							Cards.FromName("Frothing Berserker"),
							Cards.FromName("Livewire Lance"),
							Cards.FromName("Livewire Lance"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Kor'kron Elite"),
							Cards.FromName("Kor'kron Elite"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Leeroy Jenkins"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Grommash Hellscream"),
						}
						),
				new Deck(
						"Control_Warrior4",
						3500,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Whirlwind"),
							Cards.FromName("Whirlwind"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Plague of Wrath"),
							Cards.FromName("Plague of Wrath"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Armagedillo"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior5",
						3200,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Into the Fray"),
							Cards.FromName("Into the Fray"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Bronze Gatekeeper"),
							Cards.FromName("Infested Goblin"),
							Cards.FromName("Infested Goblin"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Armagedillo"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Tomb Warden"),
						}
						),
				new Deck(
						"Control_Warrior6",
						2700,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Plague of Wrath"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Warrior1",
						2600,
						new List<Card>
						{
							Cards.FromName("Inner Rage"),
							Cards.FromName("Inner Rage"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Upgrade!"),
							Cards.FromName("Upgrade!"),
							Cards.FromName("Amani Berserker"),
							Cards.FromName("Amani Berserker"),
							Cards.FromName("Cruel Taskmaster"),
							Cards.FromName("Cruel Taskmaster"),
							Cards.FromName("Rampage"),
							Cards.FromName("Rampage"),
							Cards.FromName("Temple Berserker"),
							Cards.FromName("Temple Berserker"),
							Cards.FromName("Bloodsworn Mercenary"),
							Cards.FromName("Bloodsworn Mercenary"),
							Cards.FromName("Frothing Berserker"),
							Cards.FromName("Frothing Berserker"),
							Cards.FromName("Livewire Lance"),
							Cards.FromName("Livewire Lance"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Kor'kron Elite"),
							Cards.FromName("Kor'kron Elite"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Arcanite Reaper"),
							Cards.FromName("Arcanite Reaper"),
							Cards.FromName("Leeroy Jenkins"),
						}
						),
				new Deck(
						"Control_Warrior7",
						2600,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Execute"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior8",
						2400,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Plague of Wrath"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Armagedillo"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior9",
						2100,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Azalina Soulthief"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior10",
						2100,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Baleful Banker"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Plague of Wrath"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior11",
						2000,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Bomb_Warrior5",
						2000,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Execute"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Brawl"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Azalina Soulthief"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
						}
						),
				new Deck(
						"Control_Warrior12",
						1900,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Azalina Soulthief"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior13",
						1500,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior14",
						1500,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Execute"),
							Cards.FromName("Execute"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Aggro_Warrior3",
						1500,
						new List<Card>
						{
							Cards.FromName("Inner Rage"),
							Cards.FromName("Inner Rage"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Armorsmith"),
							Cards.FromName("Armorsmith"),
							Cards.FromName("Battle Rage"),
							Cards.FromName("Battle Rage"),
							Cards.FromName("Execute"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Bloodsworn Mercenary"),
							Cards.FromName("Bloodsworn Mercenary"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Frothing Berserker"),
							Cards.FromName("Frothing Berserker"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Grommash Hellscream"),
						}
						),
				new Deck(
						"Control_Warrior15",
						1500,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Plague of Wrath"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Armagedillo"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Bomb_Warrior6",
						1400,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Bomb_Warrior7",
						1300,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Loot Hoarder"),
							Cards.FromName("Loot Hoarder"),
							Cards.FromName("Slam"),
							Cards.FromName("Slam"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Rabid Worgen"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Captain Greenskin"),
							Cards.FromName("Darius Crowley"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
						}
						),
				new Deck(
						"Bomb_Warrior8",
						1300,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Mechathun_Warrior1",
						1300,
						new List<Card>
						{
							Cards.FromName("Inner Rage"),
							Cards.FromName("Devastate"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Da Undatakah"),
							Cards.FromName("Jepetto Joybuzz"),
							Cards.FromName("Mecha'thun"),
						}
						),
				new Deck(
						"Bomb_Warrior9",
						1200,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Slam"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Seaforium Bomber"),
							Cards.FromName("Seaforium Bomber"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Quest_Warrior1",
						1200,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Hack the System"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Upgrade!"),
							Cards.FromName("Upgrade!"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Livewire Lance"),
							Cards.FromName("Livewire Lance"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Plague of Wrath"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Armored Goon"),
							Cards.FromName("Armored Goon"),
							Cards.FromName("Sul'thraze"),
							Cards.FromName("Sul'thraze"),
						}
						),
				new Deck(
						"Control_Warrior16",
						1200,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Bomb_Warrior10",
						1100,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
						}
						),
				new Deck(
						"Control_Warrior17",
						1100,
						new List<Card>
						{
							Cards.FromName("Into the Fray"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Livewire Lance"),
							Cards.FromName("Livewire Lance"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Hecklebot"),
							Cards.FromName("Hecklebot"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Armagedillo"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Tomb Warden"),
						}
						),
				new Deck(
						"Control_Warrior18",
						1000,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Chef Nomi"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Mechathun_Warrior2",
						1000,
						new List<Card>
						{
							Cards.FromName("Inner Rage"),
							Cards.FromName("Devastate"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Da Undatakah"),
							Cards.FromName("Jepetto Joybuzz"),
							Cards.FromName("Mecha'thun"),
						}
						),
				new Deck(
						"Bomb_Warrior11",
						930,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Spirit of the Rhino"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Woodcutter's Axe"),
							Cards.FromName("Woodcutter's Axe"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Rabid Worgen"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Darius Crowley"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Seaforium Bomber"),
							Cards.FromName("Seaforium Bomber"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Safeguard"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Countess Ashmore"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Akali, the Rhino"),
							Cards.FromName("Batterhead"),
							Cards.FromName("Batterhead"),
						}
						),
				new Deck(
						"Control_Warrior19",
						910,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Bomb_Warrior12",
						840,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior20",
						800,
						new List<Card>
						{
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Whirlwind"),
							Cards.FromName("Execute"),
							Cards.FromName("Execute"),
							Cards.FromName("Slam"),
							Cards.FromName("Slam"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Amani War Bear"),
							Cards.FromName("Amani War Bear"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Akali, the Rhino"),
							Cards.FromName("Grommash Hellscream"),
							Cards.FromName("Oondasta"),
							Cards.FromName("The Boomship"),
							Cards.FromName("Colossus of the Moon"),
							Cards.FromName("Dimensional Ripper"),
							Cards.FromName("Dimensional Ripper"),
							Cards.FromName("The Boom Reaver"),
						}
						),
				new Deck(
						"Bomb_Warrior13",
						800,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
						}
						),
				new Deck(
						"Control_Warrior21",
						800,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Armagedillo"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior22",
						790,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior23",
						760,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Siamat"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior24",
						750,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Execute"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Quest_Warrior2",
						740,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Hack the System"),
							Cards.FromName("Improve Morale"),
							Cards.FromName("Improve Morale"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Upgrade!"),
							Cards.FromName("Upgrade!"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Slam"),
							Cards.FromName("Slam"),
							Cards.FromName("Woodcutter's Axe"),
							Cards.FromName("Woodcutter's Axe"),
							Cards.FromName("Livewire Lance"),
							Cards.FromName("Livewire Lance"),
							Cards.FromName("Rabid Worgen"),
							Cards.FromName("Arathi Weaponsmith"),
							Cards.FromName("Arathi Weaponsmith"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Dread Corsair"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Captain Greenskin"),
							Cards.FromName("Darius Crowley"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Sul'thraze"),
						}
						),
				new Deck(
						"Control_Warrior25",
						730,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Acidic Swamp Ooze"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Bomb_Warrior14",
						700,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Improve Morale"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Armorsmith"),
							Cards.FromName("Armorsmith"),
							Cards.FromName("Battle Rage"),
							Cards.FromName("Battle Rage"),
							Cards.FromName("Cruel Taskmaster"),
							Cards.FromName("Cruel Taskmaster"),
							Cards.FromName("Execute"),
							Cards.FromName("Execute"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Brawl"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Sul'thraze"),
							Cards.FromName("Azalina Soulthief"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Grommash Hellscream"),
						}
						),
				new Deck(
						"Quest_Warrior3",
						660,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Hack the System"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Armorsmith"),
							Cards.FromName("Armorsmith"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Overlord's Whip"),
							Cards.FromName("Overlord's Whip"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Armored Goon"),
							Cards.FromName("Armored Goon"),
							Cards.FromName("Sul'thraze"),
							Cards.FromName("Sul'thraze"),
						}
						),
				new Deck(
						"Mechathun_Warrior3",
						630,
						new List<Card>
						{
							Cards.FromName("Inner Rage"),
							Cards.FromName("Inner Rage"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Whirlwind"),
							Cards.FromName("Slam"),
							Cards.FromName("Slam"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Malygos"),
							Cards.FromName("The Boomship"),
							Cards.FromName("Mecha'thun"),
						}
						),
				new Deck(
						"Control_Warrior26",
						610,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Execute"),
							Cards.FromName("Execute"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Youthful Brewmaster"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior27",
						610,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Warrior2",
						600,
						new List<Card>
						{
							Cards.FromName("Hack the System"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Upgrade!"),
							Cards.FromName("Upgrade!"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Woodcutter's Axe"),
							Cards.FromName("Woodcutter's Axe"),
							Cards.FromName("Hench-Clan Thug"),
							Cards.FromName("Hench-Clan Thug"),
							Cards.FromName("Livewire Lance"),
							Cards.FromName("Livewire Lance"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Arathi Weaponsmith"),
							Cards.FromName("Arathi Weaponsmith"),
							Cards.FromName("Kor'kron Elite"),
							Cards.FromName("Kor'kron Elite"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Arcanite Reaper"),
							Cards.FromName("Arcanite Reaper"),
							Cards.FromName("Captain Greenskin"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Armored Goon"),
							Cards.FromName("Armored Goon"),
							Cards.FromName("Sul'thraze"),
						}
						),
				new Deck(
						"Control_Warrior28",
						590,
						new List<Card>
						{
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Whirlwind"),
							Cards.FromName("Execute"),
							Cards.FromName("Execute"),
							Cards.FromName("Slam"),
							Cards.FromName("Slam"),
							Cards.FromName("Sweeping Strikes"),
							Cards.FromName("Sweeping Strikes"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Witchwood Grizzly"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Amani War Bear"),
							Cards.FromName("Amani War Bear"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Akali, the Rhino"),
							Cards.FromName("Grommash Hellscream"),
							Cards.FromName("Oondasta"),
							Cards.FromName("The Boomship"),
							Cards.FromName("Dimensional Ripper"),
							Cards.FromName("Dimensional Ripper"),
							Cards.FromName("The Boom Reaver"),
						}
						),
				new Deck(
						"Warrior3",
						560,
						new List<Card>
						{
							Cards.FromName("Devastate"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Dragon Roar"),
							Cards.FromName("Dragon Roar"),
							Cards.FromName("Firetree Witchdoctor"),
							Cards.FromName("Firetree Witchdoctor"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Smolderthorn Lancer"),
							Cards.FromName("Smolderthorn Lancer"),
							Cards.FromName("Proud Defender"),
							Cards.FromName("Proud Defender"),
							Cards.FromName("Scaleworm"),
							Cards.FromName("Scaleworm"),
							Cards.FromName("War Master Voone"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Dragonmaw Scorcher"),
							Cards.FromName("Dragonmaw Scorcher"),
							Cards.FromName("Emberscale Drake"),
							Cards.FromName("Emberscale Drake"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Crowd Roaster"),
							Cards.FromName("Crowd Roaster"),
							Cards.FromName("Ysera"),
						}
						),
				new Deck(
						"Bomb_Warrior15",
						550,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
						}
						),
				new Deck(
						"Warrior4",
						540,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Plague of Wrath"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Armagedillo"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Aggro_Warrior4",
						520,
						new List<Card>
						{
							Cards.FromName("Inner Rage"),
							Cards.FromName("Inner Rage"),
							Cards.FromName("Devastate"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Amani Berserker"),
							Cards.FromName("Amani Berserker"),
							Cards.FromName("Battle Rage"),
							Cards.FromName("Battle Rage"),
							Cards.FromName("Cruel Taskmaster"),
							Cards.FromName("Cruel Taskmaster"),
							Cards.FromName("Rampage"),
							Cards.FromName("Rampage"),
							Cards.FromName("Redband Wasp"),
							Cards.FromName("Redband Wasp"),
							Cards.FromName("Upgradeable Framebot"),
							Cards.FromName("Upgradeable Framebot"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Bloodsworn Mercenary"),
							Cards.FromName("Bloodsworn Mercenary"),
							Cards.FromName("Frothing Berserker"),
							Cards.FromName("Frothing Berserker"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Kor'kron Elite"),
							Cards.FromName("Kor'kron Elite"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Leeroy Jenkins"),
						}
						),
				new Deck(
						"Control_Warrior29",
						510,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Darius Crowley"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Bomb_Warrior16",
						510,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Execute"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Brawl"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Bomb_Warrior17",
						510,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Improve Morale"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Armorsmith"),
							Cards.FromName("Armorsmith"),
							Cards.FromName("Battle Rage"),
							Cards.FromName("Battle Rage"),
							Cards.FromName("Cruel Taskmaster"),
							Cards.FromName("Cruel Taskmaster"),
							Cards.FromName("Execute"),
							Cards.FromName("Execute"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Spellbreaker"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Brawl"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Sul'thraze"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Grommash Hellscream"),
						}
						),
				new Deck(
						"Control_Warrior30",
						490,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Plague of Wrath"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Armagedillo"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Bomb_Warrior18",
						480,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Clockwork Goblin"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Wrenchcalibur"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Blastmaster Boom"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior31",
						460,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Plague of Wrath"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Armagedillo"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior32",
						460,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Youthful Brewmaster"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior33",
						450,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Aggro_Warrior5",
						440,
						new List<Card>
						{
							Cards.FromName("Inner Rage"),
							Cards.FromName("Inner Rage"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Improve Morale"),
							Cards.FromName("Improve Morale"),
							Cards.FromName("Amani Berserker"),
							Cards.FromName("Amani Berserker"),
							Cards.FromName("Armorsmith"),
							Cards.FromName("Armorsmith"),
							Cards.FromName("Battle Rage"),
							Cards.FromName("Battle Rage"),
							Cards.FromName("Cruel Taskmaster"),
							Cards.FromName("Cruel Taskmaster"),
							Cards.FromName("Execute"),
							Cards.FromName("Execute"),
							Cards.FromName("Loot Hoarder"),
							Cards.FromName("Loot Hoarder"),
							Cards.FromName("Rampage"),
							Cards.FromName("Rampage"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Acolyte of Pain"),
							Cards.FromName("Bloodsworn Mercenary"),
							Cards.FromName("Bloodsworn Mercenary"),
							Cards.FromName("Frothing Berserker"),
							Cards.FromName("Frothing Berserker"),
							Cards.FromName("Kor'kron Elite"),
							Cards.FromName("Kor'kron Elite"),
						}
						),
				new Deck(
						"Control_Warrior34",
						410,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Youthful Brewmaster"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Faceless Manipulator"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior35",
						410,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Frightened Flunky"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Restless Mummy"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Plague of Wrath"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Armagedillo"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Tomb Warden"),
							Cards.FromName("Tomb Warden"),
						}
						),
				new Deck(
						"Control_Warrior36",
						410,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						),
				new Deck(
						"Control_Warrior37",
						410,
						new List<Card>
						{
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Eternium Rover"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Omega Assembly"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Shield Slam"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Town Crier"),
							Cards.FromName("Execute"),
							Cards.FromName("Warpath"),
							Cards.FromName("Warpath"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Weapons Project"),
							Cards.FromName("Ironbeak Owl"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Shield Block"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Militia Commander"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Omega Devastator"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Brawl"),
							Cards.FromName("Brawl"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Dyn-o-matic"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Supercollider"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Dr. Boom, Mad Genius"),
							Cards.FromName("Archivist Elysiana"),
						}
						)
				};
		}
	}
}