using System.Collections.Generic;
using SabberStoneCore.Model;
using SabberStoneCore.Enums;

namespace SabberStoneCoreAi.Meta
{
	public class SHAMANDecks
	{
		public List<Deck> decks;

		public SHAMANDecks()
		{
			decks = new List<Deck> {
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman1",
						19000,
						new List<Card>
						{
							Cards.FromName("Mutate"),
							Cards.FromName("Mutate"),
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Former Champ"),
							Cards.FromName("Former Champ"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Murloc_Shaman1",
						12000,
						new List<Card>
						{
							Cards.FromName("Earth Shock"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Aggro_Overload_Shaman1",
						11000,
						new List<Card>
						{
							Cards.FromName("Zap!"),
							Cards.FromName("Zap!"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Likkim"),
							Cards.FromName("Likkim"),
							Cards.FromName("Rockbiter Weapon"),
							Cards.FromName("Rockbiter Weapon"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Haunting Visions"),
							Cards.FromName("Lava Burst"),
							Cards.FromName("Lava Burst"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Doomhammer"),
							Cards.FromName("Doomhammer"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Aggro_Overload_Shaman2",
						10000,
						new List<Card>
						{
							Cards.FromName("Zap!"),
							Cards.FromName("Zap!"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Likkim"),
							Cards.FromName("Likkim"),
							Cards.FromName("Rockbiter Weapon"),
							Cards.FromName("Rockbiter Weapon"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Lava Burst"),
							Cards.FromName("Lava Burst"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Doomhammer"),
							Cards.FromName("Doomhammer"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman2",
						9500,
						new List<Card>
						{
							Cards.FromName("Mutate"),
							Cards.FromName("Mutate"),
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Former Champ"),
							Cards.FromName("Former Champ"),
							Cards.FromName("Fire Elemental"),
							Cards.FromName("Fire Elemental"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman3",
						8000,
						new List<Card>
						{
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Menacing Nimbus"),
							Cards.FromName("Menacing Nimbus"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Siamat"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman4",
						5100,
						new List<Card>
						{
							Cards.FromName("Zap!"),
							Cards.FromName("Zap!"),
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Menacing Nimbus"),
							Cards.FromName("Menacing Nimbus"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Witchwood Piper"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Earthquake"),
							Cards.FromName("Earthquake"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Jepetto Joybuzz"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Murloc_Shaman2",
						4100,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Raider"),
							Cards.FromName("Murloc Raider"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Ghost Light Angler"),
							Cards.FromName("Ghost Light Angler"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Scargil"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Aggro_Overload_Shaman3",
						3600,
						new List<Card>
						{
							Cards.FromName("Zap!"),
							Cards.FromName("Zap!"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Likkim"),
							Cards.FromName("Likkim"),
							Cards.FromName("Rockbiter Weapon"),
							Cards.FromName("Rockbiter Weapon"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Electra Stormsurge"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Haunting Visions"),
							Cards.FromName("Lava Burst"),
							Cards.FromName("Lava Burst"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Doomhammer"),
							Cards.FromName("Doomhammer"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Aggro_Overload_Shaman4",
						3300,
						new List<Card>
						{
							Cards.FromName("Zap!"),
							Cards.FromName("Zap!"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Likkim"),
							Cards.FromName("Likkim"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Haunting Visions"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Vessina"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Mogu Fleshshaper"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Murloc_Shaman3",
						2600,
						new List<Card>
						{
							Cards.FromName("Earth Shock"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Scargil"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman5",
						2300,
						new List<Card>
						{
							Cards.FromName("Beaming Sidekick"),
							Cards.FromName("Beaming Sidekick"),
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Witch's Apprentice"),
							Cards.FromName("Witch's Apprentice"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Menacing Nimbus"),
							Cards.FromName("Menacing Nimbus"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Siamat"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Aggro_Overload_Shaman5",
						2300,
						new List<Card>
						{
							Cards.FromName("Zap!"),
							Cards.FromName("Zap!"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Likkim"),
							Cards.FromName("Likkim"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Vessina"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Mogu Fleshshaper"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Aggro_Overload_Shaman6",
						2200,
						new List<Card>
						{
							Cards.FromName("Mutate"),
							Cards.FromName("Mutate"),
							Cards.FromName("Zap!"),
							Cards.FromName("Zap!"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Likkim"),
							Cards.FromName("Likkim"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Storm Chaser"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Former Champ"),
							Cards.FromName("Former Champ"),
							Cards.FromName("The Storm Bringer"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Jepetto Joybuzz"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Murloc_Shaman4",
						2200,
						new List<Card>
						{
							Cards.FromName("Earth Shock"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Harrison Jones"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Murloc_Shaman5",
						2200,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Fishflinger"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Scargil"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Aggro_Overload_Shaman7",
						2000,
						new List<Card>
						{
							Cards.FromName("Zap!"),
							Cards.FromName("Zap!"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Likkim"),
							Cards.FromName("Likkim"),
							Cards.FromName("Rockbiter Weapon"),
							Cards.FromName("Rockbiter Weapon"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Electra Stormsurge"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Lava Burst"),
							Cards.FromName("Lava Burst"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Unbound Elemental"),
							Cards.FromName("Unbound Elemental"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Doomhammer"),
							Cards.FromName("Doomhammer"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Big_Shaman1",
						2000,
						new List<Card>
						{
							Cards.FromName("Totemic Smash"),
							Cards.FromName("Totemic Smash"),
							Cards.FromName("Ancestral Spirit"),
							Cards.FromName("Ancestral Spirit"),
							Cards.FromName("Big Bad Voodoo"),
							Cards.FromName("Big Bad Voodoo"),
							Cards.FromName("Far Sight"),
							Cards.FromName("Far Sight"),
							Cards.FromName("Haunting Visions"),
							Cards.FromName("Haunting Visions"),
							Cards.FromName("Lightning Storm"),
							Cards.FromName("Lightning Storm"),
							Cards.FromName("Hex"),
							Cards.FromName("Hex"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Muckmorpher"),
							Cards.FromName("Muckmorpher"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Eureka!"),
							Cards.FromName("Eureka!"),
							Cards.FromName("Rain of Toads"),
							Cards.FromName("Rain of Toads"),
							Cards.FromName("Al'Akir the Windlord"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Ysera"),
							Cards.FromName("Big Bad Archmage"),
							Cards.FromName("Big Bad Archmage"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Aggro_Overload_Shaman8",
						2000,
						new List<Card>
						{
							Cards.FromName("Zap!"),
							Cards.FromName("Zap!"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Likkim"),
							Cards.FromName("Likkim"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("The Storm Bringer"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman6",
						1900,
						new List<Card>
						{
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Menacing Nimbus"),
							Cards.FromName("Menacing Nimbus"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Seaforium Bomber"),
							Cards.FromName("Seaforium Bomber"),
							Cards.FromName("Siamat"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman7",
						1900,
						new List<Card>
						{
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Plague of Murlocs"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Hex"),
							Cards.FromName("Hex"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Seaforium Bomber"),
							Cards.FromName("Seaforium Bomber"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Earthquake"),
							Cards.FromName("Earthquake"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Jepetto Joybuzz"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Shaman1",
						1800,
						new List<Card>
						{
							Cards.FromName("Earth Shock"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Firetree Witchdoctor"),
							Cards.FromName("Firetree Witchdoctor"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Witch's Brew"),
							Cards.FromName("Brightwing"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Hex"),
							Cards.FromName("Hex"),
							Cards.FromName("Scaleworm"),
							Cards.FromName("Scaleworm"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Crowd Roaster"),
							Cards.FromName("Crowd Roaster"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Archivist Elysiana"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Murloc_Shaman6",
						1700,
						new List<Card>
						{
							Cards.FromName("Earth Shock"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Aggro_Overload_Shaman9",
						1600,
						new List<Card>
						{
							Cards.FromName("Zap!"),
							Cards.FromName("Zap!"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Likkim"),
							Cards.FromName("Likkim"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Haunting Visions"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Vessina"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Mogu Fleshshaper"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman8",
						1500,
						new List<Card>
						{
							Cards.FromName("Mutate"),
							Cards.FromName("Mutate"),
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Vessina"),
							Cards.FromName("Former Champ"),
							Cards.FromName("Former Champ"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Shaman2",
						1400,
						new List<Card>
						{
							Cards.FromName("Mutate"),
							Cards.FromName("Mutate"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Witch's Brew"),
							Cards.FromName("Electra Stormsurge"),
							Cards.FromName("Far Sight"),
							Cards.FromName("Lightning Storm"),
							Cards.FromName("Lightning Storm"),
							Cards.FromName("Mana Tide Totem"),
							Cards.FromName("Mana Tide Totem"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Hecklebot"),
							Cards.FromName("Hecklebot"),
							Cards.FromName("Hex"),
							Cards.FromName("Hex"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Krag'wa, the Frog"),
							Cards.FromName("Unseen Saboteur"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Archivist Elysiana"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Aggro_Overload_Shaman10",
						1300,
						new List<Card>
						{
							Cards.FromName("Zap!"),
							Cards.FromName("Zap!"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Likkim"),
							Cards.FromName("Likkim"),
							Cards.FromName("Rockbiter Weapon"),
							Cards.FromName("Rockbiter Weapon"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Electra Stormsurge"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Lava Burst"),
							Cards.FromName("Lava Burst"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Doomhammer"),
							Cards.FromName("Doomhammer"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman9",
						1300,
						new List<Card>
						{
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Witch's Brew"),
							Cards.FromName("Far Sight"),
							Cards.FromName("Far Sight"),
							Cards.FromName("Lightning Storm"),
							Cards.FromName("Lightning Storm"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Hex"),
							Cards.FromName("Hex"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Storm Chaser"),
							Cards.FromName("Witchwood Piper"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("The Storm Bringer"),
							Cards.FromName("Siamat"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Jepetto Joybuzz"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Murloc_Shaman7",
						1300,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Raider"),
							Cards.FromName("Murloc Raider"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Ghost Light Angler"),
							Cards.FromName("Ghost Light Angler"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman10",
						1200,
						new List<Card>
						{
							Cards.FromName("Mutate"),
							Cards.FromName("Mutate"),
							Cards.FromName("Beaming Sidekick"),
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Hungry Crab"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Quicksand Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Witchwood Piper"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Siamat"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman11",
						1200,
						new List<Card>
						{
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Plague of Murlocs"),
							Cards.FromName("Plague of Murlocs"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Former Champ"),
							Cards.FromName("Former Champ"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Siamat"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman12",
						1200,
						new List<Card>
						{
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Acidic Swamp Ooze"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Witch's Brew"),
							Cards.FromName("Witch's Brew"),
							Cards.FromName("Lightning Storm"),
							Cards.FromName("Plague of Murlocs"),
							Cards.FromName("Plague of Murlocs"),
							Cards.FromName("Storm Chaser"),
							Cards.FromName("Storm Chaser"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Earthquake"),
							Cards.FromName("Earthquake"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Archivist Elysiana"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Aggro_Overload_Shaman11",
						1000,
						new List<Card>
						{
							Cards.FromName("Zap!"),
							Cards.FromName("Zap!"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Likkim"),
							Cards.FromName("Likkim"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Storm Chaser"),
							Cards.FromName("Storm Chaser"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Sunreaver Warmage"),
							Cards.FromName("Sunreaver Warmage"),
							Cards.FromName("Rain of Toads"),
							Cards.FromName("Rain of Toads"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman13",
						1000,
						new List<Card>
						{
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Former Champ"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Siamat"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Jepetto Joybuzz"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Shaman3",
						1000,
						new List<Card>
						{
							Cards.FromName("Ancestral Healing"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Totemic Smash"),
							Cards.FromName("Totemic Smash"),
							Cards.FromName("Acidic Swamp Ooze"),
							Cards.FromName("Ancestral Spirit"),
							Cards.FromName("Ancestral Spirit"),
							Cards.FromName("Witch's Brew"),
							Cards.FromName("Far Sight"),
							Cards.FromName("Far Sight"),
							Cards.FromName("Haunting Visions"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Zentimo"),
							Cards.FromName("Hex"),
							Cards.FromName("Hex"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Archivist Elysiana"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman14",
						1000,
						new List<Card>
						{
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Elven Archer"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Belligerent Gnome"),
							Cards.FromName("Belligerent Gnome"),
							Cards.FromName("Cheaty Anklebiter"),
							Cards.FromName("Cheaty Anklebiter"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Witchwood Piper"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman15",
						970,
						new List<Card>
						{
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Seaforium Bomber"),
							Cards.FromName("Seaforium Bomber"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Earthquake"),
							Cards.FromName("Earthquake"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Jepetto Joybuzz"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman16",
						930,
						new List<Card>
						{
							Cards.FromName("Mutate"),
							Cards.FromName("Mutate"),
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Novice Engineer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Former Champ"),
							Cards.FromName("Former Champ"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Murloc_Shaman8",
						860,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Raider"),
							Cards.FromName("Murloc Raider"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Bluegill Warrior"),
							Cards.FromName("Ghost Light Angler"),
							Cards.FromName("Ghost Light Angler"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Scargil"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("The Storm Bringer"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Aggro_Overload_Shaman12",
						800,
						new List<Card>
						{
							Cards.FromName("Zap!"),
							Cards.FromName("Zap!"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Likkim"),
							Cards.FromName("Likkim"),
							Cards.FromName("Rockbiter Weapon"),
							Cards.FromName("Rockbiter Weapon"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Lava Burst"),
							Cards.FromName("Lava Burst"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Unbound Elemental"),
							Cards.FromName("Unbound Elemental"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Doomhammer"),
							Cards.FromName("Doomhammer"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Big_Shaman2",
						690,
						new List<Card>
						{
							Cards.FromName("Ancestral Healing"),
							Cards.FromName("Ancestral Healing"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Ancestral Spirit"),
							Cards.FromName("Ancestral Spirit"),
							Cards.FromName("Big Bad Voodoo"),
							Cards.FromName("Big Bad Voodoo"),
							Cards.FromName("Witch's Brew"),
							Cards.FromName("Far Sight"),
							Cards.FromName("Far Sight"),
							Cards.FromName("Haunting Visions"),
							Cards.FromName("Haunting Visions"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Hex"),
							Cards.FromName("Hex"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Muckmorpher"),
							Cards.FromName("Muckmorpher"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Cairne Bloodhoof"),
							Cards.FromName("Eureka!"),
							Cards.FromName("Eureka!"),
							Cards.FromName("Al'Akir the Windlord"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Ysera"),
							Cards.FromName("Big Bad Archmage"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Aggro_Overload_Shaman13",
						680,
						new List<Card>
						{
							Cards.FromName("Mutate"),
							Cards.FromName("Mutate"),
							Cards.FromName("Zap!"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murmy"),
							Cards.FromName("Murmy"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Vessina"),
							Cards.FromName("Former Champ"),
							Cards.FromName("Former Champ"),
							Cards.FromName("The Storm Bringer"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Hagatha the Witch"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Murloc_Shaman9",
						670,
						new List<Card>
						{
							Cards.FromName("Earth Shock"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman17",
						650,
						new List<Card>
						{
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Menacing Nimbus"),
							Cards.FromName("Menacing Nimbus"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Hex"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Seaforium Bomber"),
							Cards.FromName("Seaforium Bomber"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Siamat"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Murloc_Shaman10",
						600,
						new List<Card>
						{
							Cards.FromName("Earth Shock"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Scargil"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Big_Shaman3",
						580,
						new List<Card>
						{
							Cards.FromName("Ancestral Healing"),
							Cards.FromName("Ancestral Healing"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Ancestral Spirit"),
							Cards.FromName("Ancestral Spirit"),
							Cards.FromName("Big Bad Voodoo"),
							Cards.FromName("Big Bad Voodoo"),
							Cards.FromName("Witch's Brew"),
							Cards.FromName("Far Sight"),
							Cards.FromName("Far Sight"),
							Cards.FromName("Haunting Visions"),
							Cards.FromName("Haunting Visions"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Hex"),
							Cards.FromName("Hex"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Muckmorpher"),
							Cards.FromName("Muckmorpher"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Eureka!"),
							Cards.FromName("Eureka!"),
							Cards.FromName("Al'Akir the Windlord"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Ysera"),
							Cards.FromName("Big Bad Archmage"),
							Cards.FromName("Big Bad Archmage"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman18",
						580,
						new List<Card>
						{
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Augmented Elekk"),
							Cards.FromName("Plague of Murlocs"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Seaforium Bomber"),
							Cards.FromName("Seaforium Bomber"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Fire Elemental"),
							Cards.FromName("Earthquake"),
							Cards.FromName("Earthquake"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Jepetto Joybuzz"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Murloc_Shaman11",
						570,
						new List<Card>
						{
							Cards.FromName("Zap!"),
							Cards.FromName("Zap!"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Rain of Toads"),
							Cards.FromName("The Storm Bringer"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman19",
						540,
						new List<Card>
						{
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Menacing Nimbus"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Witch's Brew"),
							Cards.FromName("Zephrys the Great"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Far Sight"),
							Cards.FromName("Lightning Storm"),
							Cards.FromName("Mana Tide Totem"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Plague of Murlocs"),
							Cards.FromName("Vulpera Scoundrel"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Hex"),
							Cards.FromName("Storm Chaser"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Fire Elemental"),
							Cards.FromName("Earthquake"),
							Cards.FromName("Mogu Fleshshaper"),
							Cards.FromName("Siamat"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Quest_Shaman20",
						540,
						new List<Card>
						{
							Cards.FromName("Mutate"),
							Cards.FromName("Mutate"),
							Cards.FromName("Corrupt the Waters"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("EVIL Cable Rat"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Questing Explorer"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Sandstorm Elemental"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Weaponized Wasp"),
							Cards.FromName("Hex"),
							Cards.FromName("Hex"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Lifedrinker"),
							Cards.FromName("Barista Lynchen"),
							Cards.FromName("Former Champ"),
							Cards.FromName("Former Champ"),
							Cards.FromName("Fire Elemental"),
							Cards.FromName("Fire Elemental"),
							Cards.FromName("The Storm Bringer"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Siamat"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Jepetto Joybuzz"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Aggro_Overload_Shaman14",
						530,
						new List<Card>
						{
							Cards.FromName("Zap!"),
							Cards.FromName("Zap!"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("EVIL Totem"),
							Cards.FromName("Likkim"),
							Cards.FromName("Likkim"),
							Cards.FromName("Rockbiter Weapon"),
							Cards.FromName("Rockbiter Weapon"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Lava Burst"),
							Cards.FromName("Lava Burst"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Vessina"),
							Cards.FromName("Doomhammer"),
							Cards.FromName("Doomhammer"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Murloc_Shaman12",
						530,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Ghost Light Angler"),
							Cards.FromName("Ghost Light Angler"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Knife Juggler"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Cult Master"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Scargil"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Hagatha the Witch"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Murloc_Shaman13",
						530,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Belligerent Gnome"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Sunfury Protector"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Hench-Clan Hag"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Aggro_Overload_Shaman15",
						520,
						new List<Card>
						{
							Cards.FromName("Zap!"),
							Cards.FromName("Zap!"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Likkim"),
							Cards.FromName("Likkim"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Storm Chaser"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Shaman4",
						460,
						new List<Card>
						{
							Cards.FromName("Earth Shock"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Acidic Swamp Ooze"),
							Cards.FromName("Omega Mind"),
							Cards.FromName("Witch's Brew"),
							Cards.FromName("Witch's Brew"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Far Sight"),
							Cards.FromName("Far Sight"),
							Cards.FromName("Lightning Storm"),
							Cards.FromName("Mana Tide Totem"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Hex"),
							Cards.FromName("Hex"),
							Cards.FromName("Storm Chaser"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Archivist Elysiana"),
							Cards.FromName("Shudderwock"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Aggro_Overload_Shaman16",
						440,
						new List<Card>
						{
							Cards.FromName("Zap!"),
							Cards.FromName("Zap!"),
							Cards.FromName("Earth Shock"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Voltaic Burst"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Earthen Might"),
							Cards.FromName("Likkim"),
							Cards.FromName("Likkim"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Feral Spirit"),
							Cards.FromName("Haunting Visions"),
							Cards.FromName("Haunting Visions"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("Microtech Controller"),
							Cards.FromName("SN1P-SN4P"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Spirit of the Frog"),
							Cards.FromName("Hex"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Thunderhead"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("The Storm Bringer"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Murloc_Shaman14",
						420,
						new List<Card>
						{
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Grimscale Oracle"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Murloc Tidecaller"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Toxfin"),
							Cards.FromName("Ghost Light Angler"),
							Cards.FromName("Ghost Light Angler"),
							Cards.FromName("Hench-Clan Hogsteed"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Murloc Tidehunter"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Soul of the Murloc"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Underbelly Angler"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Coldlight Seer"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Murloc Warleader"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Nightmare Amalgam"),
							Cards.FromName("Cult Master"),
							Cards.FromName("Cult Master"),
							Cards.FromName("Murloc Tastyfin"),
							Cards.FromName("Scargil"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Bloodlust"),
							Cards.FromName("Hagatha the Witch"),
						}
						),
				new Deck(CardClass.SHAMAN,
						"Shaman5",
						410,
						new List<Card>
						{
							Cards.FromName("Earth Shock"),
							Cards.FromName("Lightning Bolt"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Sludge Slurper"),
							Cards.FromName("Acidic Swamp Ooze"),
							Cards.FromName("Acidic Swamp Ooze"),
							Cards.FromName("Menacing Nimbus"),
							Cards.FromName("Menacing Nimbus"),
							Cards.FromName("Witch's Brew"),
							Cards.FromName("Witch's Brew"),
							Cards.FromName("Bog Slosher"),
							Cards.FromName("Lightning Storm"),
							Cards.FromName("Mind Control Tech"),
							Cards.FromName("Hex"),
							Cards.FromName("Hex"),
							Cards.FromName("Storm Chaser"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Twilight Drake"),
							Cards.FromName("Big Game Hunter"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Hagatha's Scheme"),
							Cards.FromName("Zilliax"),
							Cards.FromName("Safeguard"),
							Cards.FromName("Giggling Inventor"),
							Cards.FromName("Swampqueen Hagatha"),
							Cards.FromName("Hagatha the Witch"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Walking Fountain"),
							Cards.FromName("Archivist Elysiana"),
							Cards.FromName("Shudderwock"),
						}
						)
				};
		}
	}
}
